"""Multilingual CRM / YBS / BI glossary content used to seed the Knowledge module."""

CATEGORIES = [
    {"key": "crm", "name_en": "CRM", "name_tr": "CRM", "name_de": "CRM", "name_ar": "إدارة علاقات العملاء", "sort_order": 1},
    {"key": "sales", "name_en": "Sales", "name_tr": "Satış", "name_de": "Vertrieb", "name_ar": "المبيعات", "sort_order": 2},
    {"key": "marketing", "name_en": "Marketing", "name_tr": "Pazarlama", "name_de": "Marketing", "name_ar": "التسويق", "sort_order": 3},
    {"key": "finance", "name_en": "Finance", "name_tr": "Finans", "name_de": "Finanzen", "name_ar": "التمويل", "sort_order": 4},
    {"key": "management", "name_en": "Management", "name_tr": "Yönetim", "name_de": "Management", "name_ar": "الإدارة", "sort_order": 5},
    {"key": "business_intelligence", "name_en": "Business Intelligence", "name_tr": "İş Zekası", "name_de": "Business Intelligence", "name_ar": "ذكاء الأعمال", "sort_order": 6},
    {"key": "ybs", "name_en": "Management Information Systems", "name_tr": "Yönetim Bilişim Sistemleri", "name_de": "Managementinformationssysteme", "name_ar": "نظم المعلومات الإدارية", "sort_order": 7},
    {"key": "software", "name_en": "Software", "name_tr": "Yazılım", "name_de": "Software", "name_ar": "البرمجيات", "sort_order": 8},
    {"key": "analytics", "name_en": "Analytics", "name_tr": "Analitik", "name_de": "Analytik", "name_ar": "التحليلات", "sort_order": 9},
]

# category_key -> list of term dicts
TERMS = [
    dict(key="crm", category="crm",
         term_en="CRM (Customer Relationship Management)", term_tr="CRM (Müşteri İlişkileri Yönetimi)",
         term_de="CRM (Kundenbeziehungsmanagement)", term_ar="إدارة علاقات العملاء (CRM)",
         short_definition_en="A system for managing a company's relationships with current and potential customers.",
         short_definition_tr="Şirketin mevcut ve potansiyel müşterileriyle ilişkilerini yönetmesini sağlayan sistem.",
         short_definition_de="Ein System zur Verwaltung der Beziehungen eines Unternehmens zu bestehenden und potenziellen Kunden.",
         short_definition_ar="نظام لإدارة علاقات الشركة مع العملاء الحاليين والمحتملين.",
         definition_en="Customer Relationship Management is the systematic approach and software system used to manage a company's interactions with current and potential customers, covering sales, marketing, and support.",
         definition_tr="CRM, bir şirketin mevcut ve potansiyel müşterileriyle olan etkileşimlerini satış, pazarlama ve destek süreçleri boyunca sistematik olarak yönetmesini sağlayan yaklaşım ve yazılım sistemidir.",
         definition_de="Customer Relationship Management ist der systematische Ansatz und das Softwaresystem, mit dem ein Unternehmen seine Interaktionen mit aktuellen und potenziellen Kunden über Vertrieb, Marketing und Support hinweg verwaltet.",
         definition_ar="إدارة علاقات العملاء هي النهج المنظم والنظام البرمجي المستخدم لإدارة تفاعلات الشركة مع العملاء الحاليين والمحتملين، وتشمل المبيعات والتسويق والدعم."),
    dict(key="lead", category="sales",
         term_en="Lead", term_tr="Aday (Lead)", term_de="Lead", term_ar="عميل محتمل (Lead)",
         short_definition_en="A person or organization with potential interest in a product, not yet a customer.",
         short_definition_tr="Ürün veya hizmetle ilgilenme potansiyeli bulunan ancak henüz müşteriye dönüşmemiş kişi veya kurum.",
         short_definition_de="Eine Person oder Organisation mit potenziellem Interesse an einem Produkt, aber noch kein Kunde.",
         short_definition_ar="شخص أو مؤسسة لديها اهتمام محتمل بمنتج أو خدمة ولم تتحول إلى عميل بعد.",
         definition_en="A lead is a person or organization that has shown potential interest in a company's product or service but has not yet become a paying customer. Leads are the entry point of the sales pipeline.",
         definition_tr="Lead, bir şirketin ürün veya hizmetiyle ilgilenme potansiyeli gösteren ancak henüz ödeme yapan bir müşteriye dönüşmemiş kişi veya kurumdur. Lead'ler satış hunisinin giriş noktasıdır.",
         definition_de="Ein Lead ist eine Person oder Organisation, die potenzielles Interesse an einem Produkt oder einer Dienstleistung eines Unternehmens gezeigt hat, aber noch kein zahlender Kunde geworden ist. Leads sind der Einstiegspunkt der Vertriebspipeline.",
         definition_ar="العميل المحتمل هو شخص أو مؤسسة أظهرت اهتمامًا محتملاً بمنتج أو خدمة شركة ما، ولكنها لم تتحول بعد إلى عميل فعلي. يمثل العملاء المحتملون نقطة الدخول إلى مسار المبيعات."),
    dict(key="opportunity", category="sales",
         term_en="Opportunity", term_tr="Fırsat (Opportunity)", term_de="Verkaufschance", term_ar="فرصة بيعية",
         short_definition_en="A qualified prospect with a realistic chance of converting into a sale.",
         short_definition_tr="Satışa dönüşme potansiyeli olan, nitelikli ticari fırsat.",
         short_definition_de="Ein qualifizierter Interessent mit einer realistischen Chance, zu einem Verkauf zu werden.",
         short_definition_ar="عميل محتمل مؤهل لديه فرصة واقعية للتحول إلى صفقة بيع.",
         definition_en="An opportunity is a qualified deal that has moved past the initial lead stage and represents a realistic, trackable chance of generating revenue.",
         definition_tr="Opportunity, ilk lead aşamasını geçmiş ve gerçekçi, takip edilebilir bir gelir potansiyeli taşıyan nitelikli bir satış fırsatıdır.",
         definition_de="Eine Opportunity ist ein qualifizierter Deal, der die anfängliche Lead-Phase durchlaufen hat und eine realistische, nachverfolgbare Chance auf Umsatz darstellt.",
         definition_ar="الفرصة البيعية هي صفقة مؤهلة تجاوزت مرحلة العميل المحتمل الأولية وتمثل فرصة واقعية وقابلة للتتبع لتحقيق إيرادات."),
    dict(key="sales_pipeline", category="sales",
         term_en="Sales Pipeline", term_tr="Satış Hunisi (Pipeline)", term_de="Vertriebspipeline", term_ar="مسار المبيعات",
         short_definition_en="The stages a deal passes through from first contact to close.",
         short_definition_tr="Bir satış fırsatının ilk temastan kapanışa kadar geçtiği aşamalar.",
         short_definition_de="Die Phasen, die ein Deal vom Erstkontakt bis zum Abschluss durchläuft.",
         short_definition_ar="المراحل التي تمر بها الصفقة من أول تواصل حتى الإغلاق.",
         definition_en="A sales pipeline shows the stages a sales opportunity passes through, from first contact to a closed-won or closed-lost outcome, giving visibility into the health and velocity of a sales team's efforts.",
         definition_tr="Satış hunisi, bir satış fırsatının ilk temastan satışın kazanılması veya kaybedilmesine kadar geçtiği aşamaları gösterir ve satış ekibinin performansına görünürlük sağlar.",
         definition_de="Eine Vertriebspipeline zeigt die Phasen, die eine Verkaufschance vom Erstkontakt bis zu einem gewonnenen oder verlorenen Abschluss durchläuft, und gibt Einblick in die Leistung des Vertriebsteams.",
         definition_ar="يوضح مسار المبيعات المراحل التي تمر بها الفرصة البيعية من أول تواصل حتى إغلاقها بالفوز أو الخسارة، مما يمنح رؤية واضحة لأداء فريق المبيعات."),
    dict(key="conversion_rate", category="analytics",
         term_en="Conversion Rate", term_tr="Dönüşüm Oranı", term_de="Konversionsrate", term_ar="معدل التحويل",
         short_definition_en="The percentage of users at one stage who move on to the next target action.",
         short_definition_tr="Belirli bir aşamadaki kullanıcıların bir sonraki hedef aksiyona dönüşme oranı.",
         short_definition_de="Der Prozentsatz der Nutzer einer Stufe, die zur nächsten Zielaktion übergehen.",
         short_definition_ar="نسبة المستخدمين في مرحلة معينة الذين ينتقلون إلى الإجراء المستهدف التالي.",
         definition_en="Conversion rate measures the percentage of entities (leads, visitors, trial users) that move from one stage of a funnel to the next target action, e.g. 100 leads producing 20 qualified leads is a 20% conversion rate.",
         definition_tr="Dönüşüm oranı, bir huninin bir aşamasından bir sonraki hedef aksiyona geçen varlıkların (lead, ziyaretçi, deneme kullanıcısı) yüzdesini ölçer. Örneğin 100 lead'den 20 nitelikli lead elde edilmesi %20 dönüşüm oranı demektir.",
         definition_de="Die Konversionsrate misst den Prozentsatz der Einheiten (Leads, Besucher, Testnutzer), die von einer Stufe eines Funnels zur nächsten Zielaktion übergehen, z. B. ergeben 100 Leads mit 20 qualifizierten Leads eine Konversionsrate von 20 %.",
         definition_ar="يقيس معدل التحويل النسبة المئوية للعناصر (العملاء المحتملون، الزوار، المستخدمون التجريبيون) التي تنتقل من مرحلة في مسار التحويل إلى الإجراء المستهدف التالي؛ فمثلاً 100 عميل محتمل ينتج عنهم 20 عميلاً مؤهلاً يعني معدل تحويل 20%.",
         example="100 Leads -> 20 Qualified Leads = 20% Conversion Rate"),
    dict(key="cac", category="finance",
         term_en="CAC (Customer Acquisition Cost)", term_tr="CAC (Müşteri Edinme Maliyeti)",
         term_de="CAC (Kundenakquisitionskosten)", term_ar="تكلفة اكتساب العميل (CAC)",
         short_definition_en="The average cost required to acquire one new customer.",
         short_definition_tr="Bir müşteriyi kazanmak için ortalama harcanan maliyet.",
         short_definition_de="Die durchschnittlichen Kosten, um einen neuen Kunden zu gewinnen.",
         short_definition_ar="التكلفة المتوسطة المطلوبة لاكتساب عميل جديد واحد.",
         definition_en="Customer Acquisition Cost is calculated by dividing total sales and marketing spend by the number of new customers acquired in a given period. It shows how much it costs to win one customer.",
         definition_tr="CAC, belirli bir dönemdeki toplam satış ve pazarlama harcamasının, o dönemde kazanılan yeni müşteri sayısına bölünmesiyle hesaplanır. Bir müşteriyi kazanmanın maliyetini gösterir.",
         definition_de="Die Kundenakquisitionskosten werden berechnet, indem die gesamten Vertriebs- und Marketingausgaben durch die Anzahl der in einem bestimmten Zeitraum gewonnenen neuen Kunden geteilt werden.",
         definition_ar="يتم حساب تكلفة اكتساب العميل بقسمة إجمالي نفقات المبيعات والتسويق على عدد العملاء الجدد الذين تم اكتسابهم خلال فترة معينة."),
    dict(key="ltv", category="finance",
         term_en="LTV (Customer Lifetime Value)", term_tr="LTV (Müşteri Yaşam Boyu Değeri)",
         term_de="LTV (Customer Lifetime Value)", term_ar="القيمة الدائمة للعميل (LTV)",
         short_definition_en="The total economic value a customer is expected to generate over the relationship.",
         short_definition_tr="Bir müşterinin şirketle ilişkisi boyunca oluşturması beklenen toplam ekonomik değer.",
         short_definition_de="Der gesamte wirtschaftliche Wert, den ein Kunde über die Beziehung hinweg voraussichtlich generiert.",
         short_definition_ar="القيمة الاقتصادية الإجمالية المتوقع أن يحققها العميل طوال فترة علاقته بالشركة.",
         definition_en="Customer Lifetime Value is the total revenue a business can reasonably expect from a single customer account throughout the business relationship. It is often compared against CAC to judge unit economics.",
         definition_tr="LTV, bir işletmenin tek bir müşteri hesabından ilişki süresi boyunca elde etmeyi bekleyebileceği toplam gelirdir. Genellikle birim ekonomisini değerlendirmek için CAC ile karşılaştırılır.",
         definition_de="Der Customer Lifetime Value ist der gesamte Umsatz, den ein Unternehmen von einem einzelnen Kundenkonto während der gesamten Geschäftsbeziehung erwarten kann. Er wird oft mit den CAC verglichen.",
         definition_ar="القيمة الدائمة للعميل هي إجمالي الإيرادات التي يمكن للشركة توقع الحصول عليها من حساب عميل واحد طوال فترة العلاقة التجارية، وتُقارن غالبًا بتكلفة الاكتساب لتقييم اقتصاديات الوحدة."),
    dict(key="churn_rate", category="finance",
         term_en="Churn Rate", term_tr="Kayıp Oranı (Churn Rate)", term_de="Abwanderungsrate", term_ar="معدل التسرب",
         short_definition_en="The rate at which customers are lost over a given period.",
         short_definition_tr="Belirli bir dönemde müşterilerin kaybedilme oranı.",
         short_definition_de="Die Rate, mit der Kunden über einen bestimmten Zeitraum verloren gehen.",
         short_definition_ar="نسبة العملاء الذين يتم فقدانهم خلال فترة زمنية معينة.",
         definition_en="Churn rate is the percentage of customers who stop doing business with a company during a given time period. Lower churn generally indicates stronger customer satisfaction and retention.",
         definition_tr="Churn rate, belirli bir zaman diliminde bir şirketle iş yapmayı bırakan müşterilerin yüzdesidir. Düşük churn genellikle daha güçlü müşteri memnuniyeti ve elde tutmayı gösterir.",
         definition_de="Die Abwanderungsrate ist der Prozentsatz der Kunden, die in einem bestimmten Zeitraum die Geschäftsbeziehung mit einem Unternehmen beenden. Eine niedrigere Abwanderungsrate deutet in der Regel auf eine stärkere Kundenzufriedenheit hin.",
         definition_ar="معدل التسرب هو النسبة المئوية للعملاء الذين يتوقفون عن التعامل مع الشركة خلال فترة زمنية معينة. يشير معدل التسرب المنخفض بشكل عام إلى رضا واحتفاظ أقوى بالعملاء."),
    dict(key="kpi", category="business_intelligence",
         term_en="KPI (Key Performance Indicator)", term_tr="KPI (Temel Performans Göstergesi)",
         term_de="KPI (Leistungskennzahl)", term_ar="مؤشر الأداء الرئيسي (KPI)",
         short_definition_en="A measurable value showing how effectively goals are being achieved.",
         short_definition_tr="Bir şirketin veya çalışanın performansını ölçmek için kullanılan temel gösterge.",
         short_definition_de="Ein messbarer Wert, der zeigt, wie effektiv Ziele erreicht werden.",
         short_definition_ar="قيمة قابلة للقياس تُظهر مدى فعالية تحقيق الأهداف.",
         definition_en="A Key Performance Indicator is a measurable value used to evaluate how effectively a company, department, or individual is achieving key business objectives, such as revenue, win rate, or conversion rate.",
         definition_tr="KPI, bir şirketin, departmanın veya çalışanın temel iş hedeflerine (gelir, kazanma oranı, dönüşüm oranı gibi) ne kadar etkili ilerlediğini değerlendirmek için kullanılan ölçülebilir bir değerdir.",
         definition_de="Eine Leistungskennzahl (KPI) ist ein messbarer Wert, der zur Bewertung herangezogen wird, wie effektiv ein Unternehmen, eine Abteilung oder eine Person zentrale Geschäftsziele wie Umsatz, Gewinnrate oder Konversionsrate erreicht.",
         definition_ar="مؤشر الأداء الرئيسي هو قيمة قابلة للقياس تُستخدم لتقييم مدى فعالية تحقيق شركة أو قسم أو فرد لأهداف الأعمال الرئيسية، مثل الإيرادات أو معدل الفوز أو معدل التحويل."),
    dict(key="forecast", category="business_intelligence",
         term_en="Forecast", term_tr="Tahmin (Forecast)", term_de="Prognose", term_ar="التوقعات (Forecast)",
         short_definition_en="A projection of expected future sales or revenue.",
         short_definition_tr="Gelecekte gerçekleşmesi beklenen satış veya gelir tahmini.",
         short_definition_de="Eine Projektion des erwarteten zukünftigen Umsatzes.",
         short_definition_ar="توقع للمبيعات أو الإيرادات المتوقعة في المستقبل.",
         definition_en="A sales forecast is a data-driven projection of expected future revenue, typically based on pipeline value, historical win rates, and deal probability.",
         definition_tr="Satış tahmini, genellikle pipeline değeri, geçmiş kazanma oranları ve fırsat olasılığına dayanan, gelecekteki beklenen gelirin veriye dayalı bir projeksiyonudur.",
         definition_de="Eine Umsatzprognose ist eine datenbasierte Projektion des erwarteten zukünftigen Umsatzes, die in der Regel auf dem Pipeline-Wert, historischen Gewinnraten und der Abschlusswahrscheinlichkeit basiert.",
         definition_ar="توقع المبيعات هو تقدير مستقبلي للإيرادات المتوقعة يعتمد على البيانات، ويُبنى عادة على قيمة خط الأنابيب البيعي ومعدلات الفوز التاريخية واحتمالية إغلاق الصفقة."),
    dict(key="mrr", category="finance",
         term_en="MRR (Monthly Recurring Revenue)", term_tr="MRR (Aylık Tekrarlayan Gelir)",
         term_de="MRR (Monatlich wiederkehrender Umsatz)", term_ar="الإيراد الشهري المتكرر (MRR)",
         short_definition_en="The predictable revenue a business expects to receive every month.",
         short_definition_tr="Bir işletmenin her ay tahsil etmeyi beklediği tekrarlayan gelir.",
         short_definition_de="Der vorhersehbare Umsatz, den ein Unternehmen jeden Monat erwartet.",
         short_definition_ar="الإيراد المتوقع الذي تحصل عليه الشركة كل شهر بشكل متكرر.",
         definition_en="Monthly Recurring Revenue is the predictable total revenue generated from all active subscriptions or recurring contracts in a given month.",
         definition_tr="MRR, belirli bir aydaki tüm aktif abonelik veya tekrarlayan sözleşmelerden elde edilen öngörülebilir toplam gelirdir.",
         definition_de="Der monatlich wiederkehrende Umsatz ist der vorhersehbare Gesamtumsatz, der aus allen aktiven Abonnements oder wiederkehrenden Verträgen in einem bestimmten Monat generiert wird.",
         definition_ar="الإيراد الشهري المتكرر هو الإجمالي المتوقع للإيرادات المتحققة من جميع الاشتراكات النشطة أو العقود المتكررة خلال شهر معين."),
    dict(key="arr", category="finance",
         term_en="ARR (Annual Recurring Revenue)", term_tr="ARR (Yıllık Tekrarlayan Gelir)",
         term_de="ARR (Jährlich wiederkehrender Umsatz)", term_ar="الإيراد السنوي المتكرر (ARR)",
         short_definition_en="Monthly Recurring Revenue annualized (MRR x 12).",
         short_definition_tr="Aylık tekrarlayan gelirin yıllıklaştırılmış hali (MRR x 12).",
         short_definition_de="Der jährlich hochgerechnete monatlich wiederkehrende Umsatz (MRR x 12).",
         short_definition_ar="الإيراد الشهري المتكرر محسوبًا على أساس سنوي (MRR × 12).",
         definition_en="Annual Recurring Revenue is the yearly value of recurring revenue from subscriptions, typically calculated as MRR multiplied by 12. It is a core SaaS growth metric.",
         definition_tr="ARR, aboneliklerden elde edilen tekrarlayan gelirin yıllık değeridir ve genellikle MRR'nin 12 ile çarpılmasıyla hesaplanır. SaaS şirketleri için temel bir büyüme metriğidir.",
         definition_de="Der jährlich wiederkehrende Umsatz ist der jährliche Wert des wiederkehrenden Umsatzes aus Abonnements, üblicherweise berechnet als MRR multipliziert mit 12.",
         definition_ar="الإيراد السنوي المتكرر هو القيمة السنوية للإيرادات المتكررة من الاشتراكات، ويُحسب عادة بضرب الإيراد الشهري المتكرر في 12."),
    dict(key="sla", category="management",
         term_en="SLA (Service Level Agreement)", term_tr="SLA (Hizmet Seviyesi Anlaşması)",
         term_de="SLA (Service Level Agreement)", term_ar="اتفاقية مستوى الخدمة (SLA)",
         short_definition_en="An agreement defining the expected level and standards of a service.",
         short_definition_tr="Bir hizmetin kalite ve süre standartlarını tanımlayan anlaşma.",
         short_definition_de="Eine Vereinbarung, die das erwartete Niveau und die Standards einer Dienstleistung definiert.",
         short_definition_ar="اتفاقية تحدد المستوى والمعايير المتوقعة لتقديم خدمة معينة.",
         definition_en="A Service Level Agreement defines the standard of service a provider commits to, including response times, uptime, and quality metrics.",
         definition_tr="SLA, bir hizmet sağlayıcının taahhüt ettiği hizmet standardını; yanıt süreleri, çalışma süresi ve kalite metriklerini tanımlar.",
         definition_de="Ein Service Level Agreement definiert den Servicestandard, zu dem sich ein Anbieter verpflichtet, einschließlich Reaktionszeiten, Verfügbarkeit und Qualitätskennzahlen.",
         definition_ar="اتفاقية مستوى الخدمة تحدد معيار الخدمة الذي يلتزم به مزود الخدمة، بما في ذلك أوقات الاستجابة ونسبة التشغيل ومقاييس الجودة."),
    dict(key="gross_margin", category="finance",
         term_en="Gross Margin", term_tr="Brüt Kâr Marjı", term_de="Bruttomarge", term_ar="الهامش الإجمالي",
         short_definition_en="Revenue remaining after subtracting the cost of goods sold, as a percentage.",
         short_definition_tr="Satılan malın maliyeti çıkarıldıktan sonra kalan gelirin yüzdesi.",
         short_definition_de="Der verbleibende Umsatz nach Abzug der Herstellungskosten, in Prozent.",
         short_definition_ar="نسبة الإيراد المتبقي بعد خصم تكلفة البضاعة المباعة.",
         definition_en="Gross margin is the percentage of revenue remaining after subtracting the direct cost of producing or delivering goods and services (COGS).",
         definition_tr="Brüt kâr marjı, mal ve hizmetlerin üretim veya teslimatının doğrudan maliyeti (COGS) çıkarıldıktan sonra kalan gelirin yüzdesidir.",
         definition_de="Die Bruttomarge ist der Prozentsatz des Umsatzes, der nach Abzug der direkten Kosten für die Herstellung oder Bereitstellung von Waren und Dienstleistungen (COGS) übrig bleibt.",
         definition_ar="الهامش الإجمالي هو النسبة المئوية للإيراد المتبقي بعد خصم التكلفة المباشرة لإنتاج أو تقديم السلع والخدمات."),
    dict(key="pipeline_velocity", category="analytics",
         term_en="Pipeline Velocity", term_tr="Pipeline Hızı (Velocity)", term_de="Pipeline-Geschwindigkeit", term_ar="سرعة خط الأنابيب البيعي",
         short_definition_en="How quickly opportunities move through the pipeline and generate revenue.",
         short_definition_tr="Satış pipeline'ındaki fırsatların ne kadar hızlı ilerlediğini ölçen metrik.",
         short_definition_de="Wie schnell Chancen die Pipeline durchlaufen und Umsatz generieren.",
         short_definition_ar="مقياس لمدى سرعة تقدم الفرص عبر خط الأنابيب البيعي وتحقيقها للإيرادات.",
         definition_en="Pipeline velocity measures how quickly deals move through the sales pipeline and translate into revenue. It is typically calculated as (number of opportunities x win rate x average deal size) / sales cycle length.",
         definition_tr="Pipeline velocity, fırsatların satış hunisinde ne kadar hızlı ilerleyip gelire dönüştüğünü ölçer. Genellikle (fırsat sayısı x kazanma oranı x ortalama fırsat büyüklüğü) / satış döngüsü uzunluğu olarak hesaplanır.",
         definition_de="Die Pipeline-Geschwindigkeit misst, wie schnell Deals die Vertriebspipeline durchlaufen und in Umsatz umgewandelt werden. Sie wird üblicherweise als (Anzahl der Chancen x Gewinnrate x durchschnittliche Dealgröße) / Verkaufszykluslänge berechnet.",
         definition_ar="تقيس سرعة خط الأنابيب البيعي مدى سرعة تقدم الصفقات عبر مسار المبيعات وتحويلها إلى إيرادات، وتُحسب عادة كـ (عدد الفرص × معدل الفوز × متوسط حجم الصفقة) ÷ مدة دورة المبيعات."),
    dict(key="win_rate", category="sales",
         term_en="Win Rate", term_tr="Kazanma Oranı (Win Rate)", term_de="Gewinnrate", term_ar="معدل الفوز",
         short_definition_en="The percentage of sales opportunities that end in a successful deal.",
         short_definition_tr="Kazanılan satış fırsatlarının toplam satış fırsatlarına oranı.",
         short_definition_de="Der Prozentsatz der Verkaufschancen, die zu einem erfolgreichen Abschluss führen.",
         short_definition_ar="النسبة المئوية للفرص البيعية التي تنتهي بصفقة ناجحة.",
         definition_en="Win rate is the percentage of sales opportunities that result in a successful (closed-won) deal, out of all opportunities that reached a final decision (won or lost).",
         definition_tr="Win rate, nihai bir karara ulaşan tüm fırsatlar (kazanılan veya kaybedilen) içinde başarıyla kapanan (kazanılan) fırsatların yüzdesidir.",
         definition_de="Die Gewinnrate ist der Prozentsatz der Verkaufschancen, die zu einem erfolgreichen (gewonnenen) Abschluss führen, gemessen an allen Chancen, die zu einer endgültigen Entscheidung (gewonnen oder verloren) gekommen sind.",
         definition_ar="معدل الفوز هو النسبة المئوية للفرص البيعية التي تنتهي بصفقة ناجحة (فوز) من إجمالي الفرص التي وصلت إلى قرار نهائي (فوز أو خسارة)."),
    dict(key="customer_360", category="crm",
         term_en="Customer 360", term_tr="360 Derece Müşteri Görünümü", term_de="Customer 360", term_ar="رؤية 360 للعميل",
         short_definition_en="A complete, unified view of a customer across every touchpoint.",
         short_definition_tr="Bir müşterinin tüm etkileşim noktalarındaki tam ve birleşik görünümü.",
         short_definition_de="Eine vollständige, einheitliche Sicht auf einen Kunden über alle Kontaktpunkte hinweg.",
         short_definition_ar="نظرة شاملة وموحدة للعميل عبر جميع نقاط التواصل.",
         definition_en="Customer 360 refers to a unified view that aggregates every interaction, deal, contact, and communication a company has had with a customer into a single profile.",
         definition_tr="Customer 360, bir şirketin bir müşteriyle olan tüm etkileşimlerini, fırsatlarını, kişilerini ve iletişim geçmişini tek bir profilde birleştiren görünümü ifade eder.",
         definition_de="Customer 360 bezeichnet eine einheitliche Sicht, die jede Interaktion, jeden Deal, Kontakt und jede Kommunikation, die ein Unternehmen mit einem Kunden hatte, in einem einzigen Profil zusammenfasst.",
         definition_ar="تشير رؤية 360 للعميل إلى عرض موحد يجمع كل تفاعل وصفقة وجهة اتصال واتصال أجرته الشركة مع العميل في ملف واحد."),
    dict(key="rbac", category="software",
         term_en="RBAC (Role-Based Access Control)", term_tr="RBAC (Rol Bazlı Erişim Kontrolü)",
         term_de="RBAC (Rollenbasierte Zugriffskontrolle)", term_ar="التحكم في الوصول المستند إلى الأدوار (RBAC)",
         short_definition_en="Restricting system access based on a user's assigned role.",
         short_definition_tr="Sistem erişiminin kullanıcının rolüne göre kısıtlanması.",
         short_definition_de="Einschränkung des Systemzugriffs basierend auf der zugewiesenen Rolle eines Benutzers.",
         short_definition_ar="تقييد الوصول إلى النظام بناءً على الدور المخصص للمستخدم.",
         definition_en="Role-Based Access Control restricts system access and actions based on a user's assigned role (e.g. Admin, Manager, Sales Rep), enforced on the backend rather than only hidden in the UI.",
         definition_tr="RBAC, sistem erişimini ve işlemleri kullanıcının atanmış rolüne (Admin, Manager, Sales Rep vb.) göre kısıtlar; bu kontrol yalnızca arayüzde değil, backend'de de uygulanır.",
         definition_de="Die rollenbasierte Zugriffskontrolle schränkt den Systemzugriff und die Aktionen basierend auf der zugewiesenen Rolle eines Benutzers (z. B. Admin, Manager, Vertriebsmitarbeiter) ein und wird im Backend durchgesetzt.",
         definition_ar="يقيّد التحكم في الوصول المستند إلى الأدوار الوصول إلى النظام والإجراءات بناءً على الدور المخصص للمستخدم (مثل المسؤول أو المدير أو مندوب المبيعات)، ويُفرض على مستوى الخادم لا الواجهة فقط."),
    dict(key="dashboard", category="business_intelligence",
         term_en="Dashboard", term_tr="Gösterge Paneli (Dashboard)", term_de="Dashboard", term_ar="لوحة المعلومات",
         short_definition_en="A visual display of key metrics for at-a-glance monitoring.",
         short_definition_tr="Temel metriklerin tek bakışta izlenmesini sağlayan görsel ekran.",
         short_definition_de="Eine visuelle Anzeige wichtiger Kennzahlen zur Überwachung auf einen Blick.",
         short_definition_ar="عرض مرئي للمقاييس الرئيسية لمتابعتها بنظرة واحدة.",
         definition_en="A dashboard is a visual interface that consolidates key performance indicators and charts into a single view, enabling managers to monitor business health at a glance.",
         definition_tr="Dashboard, temel performans göstergelerini ve grafikleri tek bir ekranda birleştiren, yöneticilerin iş sağlığını tek bakışta izlemesini sağlayan görsel bir arayüzdür.",
         definition_de="Ein Dashboard ist eine visuelle Oberfläche, die wichtige Leistungskennzahlen und Diagramme in einer einzigen Ansicht zusammenfasst, damit Manager den Geschäftszustand auf einen Blick überwachen können.",
         definition_ar="لوحة المعلومات هي واجهة مرئية تجمع مؤشرات الأداء الرئيسية والرسوم البيانية في عرض واحد، مما يتيح للمديرين متابعة صحة الأعمال بنظرة واحدة."),
    dict(key="segmentation", category="marketing",
         term_en="Customer Segmentation", term_tr="Müşteri Segmentasyonu", term_de="Kundensegmentierung", term_ar="تجزئة العملاء",
         short_definition_en="Dividing customers into groups sharing similar characteristics.",
         short_definition_tr="Müşterilerin benzer özelliklere göre gruplara ayrılması.",
         short_definition_de="Aufteilung der Kunden in Gruppen mit ähnlichen Merkmalen.",
         short_definition_ar="تقسيم العملاء إلى مجموعات تتشارك خصائص متشابهة.",
         definition_en="Customer segmentation is the practice of dividing customers into groups based on shared characteristics such as company size, industry, or revenue, so that sales and marketing efforts can be tailored effectively.",
         definition_tr="Müşteri segmentasyonu, şirket büyüklüğü, sektör veya gelir gibi ortak özelliklere göre müşterilerin gruplara ayrılması, böylece satış ve pazarlama çalışmalarının etkili şekilde uyarlanabilmesi pratiğidir.",
         definition_de="Kundensegmentierung ist die Praxis, Kunden anhand gemeinsamer Merkmale wie Unternehmensgröße, Branche oder Umsatz in Gruppen einzuteilen, damit Vertriebs- und Marketingmaßnahmen effektiv angepasst werden können.",
         definition_ar="تجزئة العملاء هي ممارسة تقسيم العملاء إلى مجموعات بناءً على خصائص مشتركة مثل حجم الشركة أو القطاع أو الإيرادات، بما يتيح تخصيص جهود المبيعات والتسويق بفعالية."),
    dict(key="ybs", category="ybs",
         term_en="Management Information System (MIS)", term_tr="Yönetim Bilişim Sistemi (YBS)",
         term_de="Managementinformationssystem (MIS)", term_ar="نظام المعلومات الإداري",
         short_definition_en="A system converting raw operational data into information for management decisions.",
         short_definition_tr="Ham operasyonel veriyi yönetim kararları için bilgiye dönüştüren sistem.",
         short_definition_de="Ein System, das operative Rohdaten in Informationen für Managemententscheidungen umwandelt.",
         short_definition_ar="نظام يحوّل البيانات التشغيلية الخام إلى معلومات تدعم قرارات الإدارة.",
         definition_en="A Management Information System collects raw operational data, processes it into structured information, and presents it as analysis that supports management decision-making - following the Data -> Information -> Analysis -> Decision chain.",
         definition_tr="Yönetim Bilişim Sistemi, ham operasyonel veriyi toplar, yapılandırılmış bilgiye dönüştürür ve yönetim kararlarını destekleyen bir analiz olarak sunar; bu, Veri -> Bilgi -> Analiz -> Karar zincirini takip eder.",
         definition_de="Ein Managementinformationssystem sammelt operative Rohdaten, verarbeitet sie zu strukturierten Informationen und präsentiert sie als Analyse, die die Managemententscheidung unterstützt - der Kette Daten -> Information -> Analyse -> Entscheidung folgend.",
         definition_ar="يجمع نظام المعلومات الإداري البيانات التشغيلية الخام، ويحوّلها إلى معلومات منظمة، ويقدمها كتحليل يدعم اتخاذ القرار الإداري، متبعًا سلسلة البيانات ← المعلومات ← التحليل ← القرار."),
    dict(key="business_intelligence", category="business_intelligence",
         term_en="Business Intelligence (BI)", term_tr="İş Zekası (BI)", term_de="Business Intelligence (BI)", term_ar="ذكاء الأعمال",
         short_definition_en="Technologies and practices for analyzing business data to support decisions.",
         short_definition_tr="İş verilerini analiz ederek karar almayı destekleyen teknoloji ve pratikler.",
         short_definition_de="Technologien und Praktiken zur Analyse von Geschäftsdaten zur Entscheidungsunterstützung.",
         short_definition_ar="تقنيات وممارسات لتحليل بيانات الأعمال لدعم اتخاذ القرار.",
         definition_en="Business Intelligence encompasses the strategies and technologies used to collect, analyze, and present business data - such as revenue trends, funnels, and segmentation - to support better management decisions.",
         definition_tr="İş zekası, gelir trendleri, huniler ve segmentasyon gibi iş verilerini toplamak, analiz etmek ve daha iyi yönetim kararlarını desteklemek için sunmakta kullanılan strateji ve teknolojileri kapsar.",
         definition_de="Business Intelligence umfasst die Strategien und Technologien zum Sammeln, Analysieren und Präsentieren von Geschäftsdaten - wie Umsatztrends, Funnels und Segmentierung - zur Unterstützung besserer Managemententscheidungen.",
         definition_ar="يشمل ذكاء الأعمال الاستراتيجيات والتقنيات المستخدمة لجمع وتحليل وتقديم بيانات الأعمال - مثل اتجاهات الإيرادات ومسارات التحويل والتجزئة - لدعم قرارات إدارية أفضل."),
    dict(key="deal", category="crm",
         term_en="Deal", term_tr="Fırsat/Anlaşma (Deal)", term_de="Deal", term_ar="صفقة",
         short_definition_en="A tracked sales transaction moving through the pipeline toward a close.",
         short_definition_tr="Pipeline içinde kapanışa doğru ilerleyen, takip edilen satış işlemi.",
         short_definition_de="Ein verfolgter Verkaufsvorgang, der sich in der Pipeline auf einen Abschluss hin bewegt.",
         short_definition_ar="عملية بيع متتبعة تتقدم عبر خط الأنابيب نحو الإغلاق.",
         definition_en="A deal is the core CRM record representing a potential sale, tracked through pipeline stages, with an associated value, probability, owner, and expected close date, until it is marked Won or Lost.",
         definition_tr="Deal, potansiyel bir satışı temsil eden, pipeline aşamaları boyunca takip edilen, değer, olasılık, sahip ve beklenen kapanış tarihi ile ilişkilendirilmiş temel CRM kaydıdır; nihayetinde Kazanıldı veya Kaybedildi olarak işaretlenir.",
         definition_de="Ein Deal ist der zentrale CRM-Datensatz, der einen potenziellen Verkauf darstellt, durch Pipeline-Phasen verfolgt wird und mit Wert, Wahrscheinlichkeit, Inhaber und erwartetem Abschlussdatum verknüpft ist, bis er als gewonnen oder verloren markiert wird.",
         definition_ar="الصفقة هي السجل الأساسي في نظام إدارة علاقات العملاء الذي يمثل عملية بيع محتملة، ويتم تتبعها عبر مراحل خط الأنابيب، مع قيمة واحتمالية ومالك وتاريخ إغلاق متوقع، حتى يتم تصنيفها كفوز أو خسارة."),
    dict(key="probability", category="sales",
         term_en="Win Probability", term_tr="Kazanma Olasılığı", term_de="Gewinnwahrscheinlichkeit", term_ar="احتمالية الفوز",
         short_definition_en="The estimated likelihood, as a percentage, that a deal will close successfully.",
         short_definition_tr="Bir fırsatın başarıyla kapanma olasılığının yüzde olarak tahmini.",
         short_definition_de="Die geschätzte Wahrscheinlichkeit in Prozent, dass ein Deal erfolgreich abgeschlossen wird.",
         short_definition_ar="التقدير الاحتمالي (كنسبة مئوية) لإغلاق الصفقة بنجاح.",
         definition_en="Win probability is a percentage estimate, usually tied to the current pipeline stage, of how likely a deal is to close as Won. It is used to calculate weighted pipeline and revenue forecasts.",
         definition_tr="Kazanma olasılığı, genellikle mevcut pipeline aşamasına bağlı olarak, bir fırsatın Kazanıldı olarak kapanma ihtimalinin yüzde tahminidir. Ağırlıklı pipeline ve gelir tahminlerinin hesaplanmasında kullanılır.",
         definition_de="Die Gewinnwahrscheinlichkeit ist eine prozentuale Schätzung, meist an die aktuelle Pipeline-Phase gekoppelt, wie wahrscheinlich ein Deal als gewonnen abgeschlossen wird. Sie wird zur Berechnung gewichteter Pipeline- und Umsatzprognosen verwendet.",
         definition_ar="احتمالية الفوز هي تقدير بالنسبة المئوية، يرتبط عادة بمرحلة خط الأنابيب الحالية، لمدى احتمال إغلاق الصفقة بالفوز، ويُستخدم لحساب تنبؤات خط الأنابيب والإيرادات المرجحة."),
    dict(key="kanban", category="software",
         term_en="Kanban Board", term_tr="Kanban Panosu", term_de="Kanban-Board", term_ar="لوحة كانبان",
         short_definition_en="A visual board showing items as cards moving through workflow columns.",
         short_definition_tr="Öğelerin iş akışı sütunları arasında hareket eden kartlar olarak gösterildiği görsel pano.",
         short_definition_de="Ein visuelles Board, das Elemente als Karten zeigt, die sich durch Workflow-Spalten bewegen.",
         short_definition_ar="لوحة مرئية تعرض العناصر كبطاقات تنتقل بين أعمدة سير العمل.",
         definition_en="A Kanban board visualizes work items (such as deals or tasks) as cards that move across columns representing workflow stages, making bottlenecks and progress immediately visible.",
         definition_tr="Kanban panosu, iş öğelerini (fırsatlar veya görevler gibi) iş akışı aşamalarını temsil eden sütunlar arasında hareket eden kartlar olarak görselleştirir, tıkanıklıkları ve ilerlemeyi anında görünür kılar.",
         definition_de="Ein Kanban-Board visualisiert Arbeitselemente (wie Deals oder Aufgaben) als Karten, die sich über Spalten bewegen, die Workflow-Phasen darstellen, wodurch Engpässe und Fortschritt sofort sichtbar werden.",
         definition_ar="تعرض لوحة كانبان عناصر العمل (مثل الصفقات أو المهام) كبطاقات تتحرك بين أعمدة تمثل مراحل سير العمل، مما يجعل الاختناقات والتقدم واضحين فورًا."),
]
