"""Multilingual CRM / YBS / BI glossary content used to seed the Knowledge module."""

CATEGORIES = [
    {
        "key": "crm",
        "name_en": "CRM",
        "name_tr": "CRM",
        "name_de": "CRM",
        "name_ar": "إدارة علاقات العملاء",
        "sort_order": 1,
    },
    {
        "key": "sales",
        "name_en": "Sales",
        "name_tr": "Satış",
        "name_de": "Vertrieb",
        "name_ar": "المبيعات",
        "sort_order": 2,
    },
    {
        "key": "marketing",
        "name_en": "Marketing",
        "name_tr": "Pazarlama",
        "name_de": "Marketing",
        "name_ar": "التسويق",
        "sort_order": 3,
    },
    {
        "key": "finance",
        "name_en": "Finance",
        "name_tr": "Finans",
        "name_de": "Finanzen",
        "name_ar": "التمويل",
        "sort_order": 4,
    },
    {
        "key": "management",
        "name_en": "Management",
        "name_tr": "Yönetim",
        "name_de": "Management",
        "name_ar": "الإدارة",
        "sort_order": 5,
    },
    {
        "key": "business_intelligence",
        "name_en": "Business Intelligence",
        "name_tr": "İş Zekası",
        "name_de": "Business Intelligence",
        "name_ar": "ذكاء الأعمال",
        "sort_order": 6,
    },
    {
        "key": "ybs",
        "name_en": "Management Information Systems",
        "name_tr": "Yönetim Bilişim Sistemleri",
        "name_de": "Managementinformationssysteme",
        "name_ar": "نظم المعلومات الإدارية",
        "sort_order": 7,
    },
    {
        "key": "software",
        "name_en": "Software",
        "name_tr": "Yazılım",
        "name_de": "Software",
        "name_ar": "البرمجيات",
        "sort_order": 8,
    },
    {
        "key": "analytics",
        "name_en": "Analytics",
        "name_tr": "Analitik",
        "name_de": "Analytik",
        "name_ar": "التحليلات",
        "sort_order": 9,
    },
]

# category_key -> list of term dicts
TERMS = [
    dict(
        key="crm",
        category="crm",
        term_en="CRM (Customer Relationship Management)",
        term_tr="CRM (Müşteri İlişkileri Yönetimi)",
        term_de="CRM (Kundenbeziehungsmanagement)",
        term_ar="إدارة علاقات العملاء (CRM)",
        short_definition_en="A system for managing a company's relationships with current and potential customers.",
        short_definition_tr="Şirketin mevcut ve potansiyel müşterileriyle ilişkilerini yönetmesini sağlayan sistem.",
        short_definition_de="Ein System zur Verwaltung der Beziehungen eines Unternehmens zu bestehenden und potenziellen Kunden.",
        short_definition_ar="نظام لإدارة علاقات الشركة مع العملاء الحاليين والمحتملين.",
        definition_en="Customer Relationship Management is the systematic approach and software system used to manage a company's interactions with current and potential customers, covering sales, marketing, and support.",
        definition_tr="CRM, bir şirketin mevcut ve potansiyel müşterileriyle olan etkileşimlerini satış, pazarlama ve destek süreçleri boyunca sistematik olarak yönetmesini sağlayan yaklaşım ve yazılım sistemidir.",
        definition_de="Customer Relationship Management ist der systematische Ansatz und das Softwaresystem, mit dem ein Unternehmen seine Interaktionen mit aktuellen und potenziellen Kunden über Vertrieb, Marketing und Support hinweg verwaltet.",
        definition_ar="إدارة علاقات العملاء هي النهج المنظم والنظام البرمجي المستخدم لإدارة تفاعلات الشركة مع العملاء الحاليين والمحتملين، وتشمل المبيعات والتسويق والدعم.",
    ),
    dict(
        key="lead",
        category="sales",
        term_en="Lead",
        term_tr="Aday (Lead)",
        term_de="Lead",
        term_ar="عميل محتمل (Lead)",
        short_definition_en="A person or organization with potential interest in a product, not yet a customer.",
        short_definition_tr="Ürün veya hizmetle ilgilenme potansiyeli bulunan ancak henüz müşteriye dönüşmemiş kişi veya kurum.",
        short_definition_de="Eine Person oder Organisation mit potenziellem Interesse an einem Produkt, aber noch kein Kunde.",
        short_definition_ar="شخص أو مؤسسة لديها اهتمام محتمل بمنتج أو خدمة ولم تتحول إلى عميل بعد.",
        definition_en="A lead is a person or organization that has shown potential interest in a company's product or service but has not yet become a paying customer. Leads are the entry point of the sales pipeline.",
        definition_tr="Lead, bir şirketin ürün veya hizmetiyle ilgilenme potansiyeli gösteren ancak henüz ödeme yapan bir müşteriye dönüşmemiş kişi veya kurumdur. Lead'ler satış hunisinin giriş noktasıdır.",
        definition_de="Ein Lead ist eine Person oder Organisation, die potenzielles Interesse an einem Produkt oder einer Dienstleistung eines Unternehmens gezeigt hat, aber noch kein zahlender Kunde geworden ist. Leads sind der Einstiegspunkt der Vertriebspipeline.",
        definition_ar="العميل المحتمل هو شخص أو مؤسسة أظهرت اهتمامًا محتملاً بمنتج أو خدمة شركة ما، ولكنها لم تتحول بعد إلى عميل فعلي. يمثل العملاء المحتملون نقطة الدخول إلى مسار المبيعات.",
    ),
    dict(
        key="opportunity",
        category="sales",
        term_en="Opportunity",
        term_tr="Fırsat (Opportunity)",
        term_de="Verkaufschance",
        term_ar="فرصة بيعية",
        short_definition_en="A qualified prospect with a realistic chance of converting into a sale.",
        short_definition_tr="Satışa dönüşme potansiyeli olan, nitelikli ticari fırsat.",
        short_definition_de="Ein qualifizierter Interessent mit einer realistischen Chance, zu einem Verkauf zu werden.",
        short_definition_ar="عميل محتمل مؤهل لديه فرصة واقعية للتحول إلى صفقة بيع.",
        definition_en="An opportunity is a qualified deal that has moved past the initial lead stage and represents a realistic, trackable chance of generating revenue.",
        definition_tr="Opportunity, ilk lead aşamasını geçmiş ve gerçekçi, takip edilebilir bir gelir potansiyeli taşıyan nitelikli bir satış fırsatıdır.",
        definition_de="Eine Opportunity ist ein qualifizierter Deal, der die anfängliche Lead-Phase durchlaufen hat und eine realistische, nachverfolgbare Chance auf Umsatz darstellt.",
        definition_ar="الفرصة البيعية هي صفقة مؤهلة تجاوزت مرحلة العميل المحتمل الأولية وتمثل فرصة واقعية وقابلة للتتبع لتحقيق إيرادات.",
    ),
    dict(
        key="sales_pipeline",
        category="sales",
        term_en="Sales Pipeline",
        term_tr="Satış Hunisi (Pipeline)",
        term_de="Vertriebspipeline",
        term_ar="مسار المبيعات",
        short_definition_en="The stages a deal passes through from first contact to close.",
        short_definition_tr="Bir satış fırsatının ilk temastan kapanışa kadar geçtiği aşamalar.",
        short_definition_de="Die Phasen, die ein Deal vom Erstkontakt bis zum Abschluss durchläuft.",
        short_definition_ar="المراحل التي تمر بها الصفقة من أول تواصل حتى الإغلاق.",
        definition_en="A sales pipeline shows the stages a sales opportunity passes through, from first contact to a closed-won or closed-lost outcome, giving visibility into the health and velocity of a sales team's efforts.",
        definition_tr="Satış hunisi, bir satış fırsatının ilk temastan satışın kazanılması veya kaybedilmesine kadar geçtiği aşamaları gösterir ve satış ekibinin performansına görünürlük sağlar.",
        definition_de="Eine Vertriebspipeline zeigt die Phasen, die eine Verkaufschance vom Erstkontakt bis zu einem gewonnenen oder verlorenen Abschluss durchläuft, und gibt Einblick in die Leistung des Vertriebsteams.",
        definition_ar="يوضح مسار المبيعات المراحل التي تمر بها الفرصة البيعية من أول تواصل حتى إغلاقها بالفوز أو الخسارة، مما يمنح رؤية واضحة لأداء فريق المبيعات.",
    ),
    dict(
        key="conversion_rate",
        category="analytics",
        term_en="Conversion Rate",
        term_tr="Dönüşüm Oranı",
        term_de="Konversionsrate",
        term_ar="معدل التحويل",
        short_definition_en="The percentage of users at one stage who move on to the next target action.",
        short_definition_tr="Belirli bir aşamadaki kullanıcıların bir sonraki hedef aksiyona dönüşme oranı.",
        short_definition_de="Der Prozentsatz der Nutzer einer Stufe, die zur nächsten Zielaktion übergehen.",
        short_definition_ar="نسبة المستخدمين في مرحلة معينة الذين ينتقلون إلى الإجراء المستهدف التالي.",
        definition_en="Conversion rate measures the percentage of entities (leads, visitors, trial users) that move from one stage of a funnel to the next target action, e.g. 100 leads producing 20 qualified leads is a 20% conversion rate.",
        definition_tr="Dönüşüm oranı, bir huninin bir aşamasından bir sonraki hedef aksiyona geçen varlıkların (lead, ziyaretçi, deneme kullanıcısı) yüzdesini ölçer. Örneğin 100 lead'den 20 nitelikli lead elde edilmesi %20 dönüşüm oranı demektir.",
        definition_de="Die Konversionsrate misst den Prozentsatz der Einheiten (Leads, Besucher, Testnutzer), die von einer Stufe eines Funnels zur nächsten Zielaktion übergehen, z. B. ergeben 100 Leads mit 20 qualifizierten Leads eine Konversionsrate von 20 %.",
        definition_ar="يقيس معدل التحويل النسبة المئوية للعناصر (العملاء المحتملون، الزوار، المستخدمون التجريبيون) التي تنتقل من مرحلة في مسار التحويل إلى الإجراء المستهدف التالي؛ فمثلاً 100 عميل محتمل ينتج عنهم 20 عميلاً مؤهلاً يعني معدل تحويل 20%.",
        example="100 Leads -> 20 Qualified Leads = 20% Conversion Rate",
    ),
    dict(
        key="cac",
        category="finance",
        term_en="CAC (Customer Acquisition Cost)",
        term_tr="CAC (Müşteri Edinme Maliyeti)",
        term_de="CAC (Kundenakquisitionskosten)",
        term_ar="تكلفة اكتساب العميل (CAC)",
        short_definition_en="The average cost required to acquire one new customer.",
        short_definition_tr="Bir müşteriyi kazanmak için ortalama harcanan maliyet.",
        short_definition_de="Die durchschnittlichen Kosten, um einen neuen Kunden zu gewinnen.",
        short_definition_ar="التكلفة المتوسطة المطلوبة لاكتساب عميل جديد واحد.",
        definition_en="Customer Acquisition Cost is calculated by dividing total sales and marketing spend by the number of new customers acquired in a given period. It shows how much it costs to win one customer.",
        definition_tr="CAC, belirli bir dönemdeki toplam satış ve pazarlama harcamasının, o dönemde kazanılan yeni müşteri sayısına bölünmesiyle hesaplanır. Bir müşteriyi kazanmanın maliyetini gösterir.",
        definition_de="Die Kundenakquisitionskosten werden berechnet, indem die gesamten Vertriebs- und Marketingausgaben durch die Anzahl der in einem bestimmten Zeitraum gewonnenen neuen Kunden geteilt werden.",
        definition_ar="يتم حساب تكلفة اكتساب العميل بقسمة إجمالي نفقات المبيعات والتسويق على عدد العملاء الجدد الذين تم اكتسابهم خلال فترة معينة.",
    ),
    dict(
        key="ltv",
        category="finance",
        term_en="LTV (Customer Lifetime Value)",
        term_tr="LTV (Müşteri Yaşam Boyu Değeri)",
        term_de="LTV (Customer Lifetime Value)",
        term_ar="القيمة الدائمة للعميل (LTV)",
        short_definition_en="The total economic value a customer is expected to generate over the relationship.",
        short_definition_tr="Bir müşterinin şirketle ilişkisi boyunca oluşturması beklenen toplam ekonomik değer.",
        short_definition_de="Der gesamte wirtschaftliche Wert, den ein Kunde über die Beziehung hinweg voraussichtlich generiert.",
        short_definition_ar="القيمة الاقتصادية الإجمالية المتوقع أن يحققها العميل طوال فترة علاقته بالشركة.",
        definition_en="Customer Lifetime Value is the total revenue a business can reasonably expect from a single customer account throughout the business relationship. It is often compared against CAC to judge unit economics.",
        definition_tr="LTV, bir işletmenin tek bir müşteri hesabından ilişki süresi boyunca elde etmeyi bekleyebileceği toplam gelirdir. Genellikle birim ekonomisini değerlendirmek için CAC ile karşılaştırılır.",
        definition_de="Der Customer Lifetime Value ist der gesamte Umsatz, den ein Unternehmen von einem einzelnen Kundenkonto während der gesamten Geschäftsbeziehung erwarten kann. Er wird oft mit den CAC verglichen.",
        definition_ar="القيمة الدائمة للعميل هي إجمالي الإيرادات التي يمكن للشركة توقع الحصول عليها من حساب عميل واحد طوال فترة العلاقة التجارية، وتُقارن غالبًا بتكلفة الاكتساب لتقييم اقتصاديات الوحدة.",
    ),
    dict(
        key="churn_rate",
        category="finance",
        term_en="Churn Rate",
        term_tr="Kayıp Oranı (Churn Rate)",
        term_de="Abwanderungsrate",
        term_ar="معدل التسرب",
        short_definition_en="The rate at which customers are lost over a given period.",
        short_definition_tr="Belirli bir dönemde müşterilerin kaybedilme oranı.",
        short_definition_de="Die Rate, mit der Kunden über einen bestimmten Zeitraum verloren gehen.",
        short_definition_ar="نسبة العملاء الذين يتم فقدانهم خلال فترة زمنية معينة.",
        definition_en="Churn rate is the percentage of customers who stop doing business with a company during a given time period. Lower churn generally indicates stronger customer satisfaction and retention.",
        definition_tr="Churn rate, belirli bir zaman diliminde bir şirketle iş yapmayı bırakan müşterilerin yüzdesidir. Düşük churn genellikle daha güçlü müşteri memnuniyeti ve elde tutmayı gösterir.",
        definition_de="Die Abwanderungsrate ist der Prozentsatz der Kunden, die in einem bestimmten Zeitraum die Geschäftsbeziehung mit einem Unternehmen beenden. Eine niedrigere Abwanderungsrate deutet in der Regel auf eine stärkere Kundenzufriedenheit hin.",
        definition_ar="معدل التسرب هو النسبة المئوية للعملاء الذين يتوقفون عن التعامل مع الشركة خلال فترة زمنية معينة. يشير معدل التسرب المنخفض بشكل عام إلى رضا واحتفاظ أقوى بالعملاء.",
    ),
    dict(
        key="kpi",
        category="business_intelligence",
        term_en="KPI (Key Performance Indicator)",
        term_tr="KPI (Temel Performans Göstergesi)",
        term_de="KPI (Leistungskennzahl)",
        term_ar="مؤشر الأداء الرئيسي (KPI)",
        short_definition_en="A measurable value showing how effectively goals are being achieved.",
        short_definition_tr="Bir şirketin veya çalışanın performansını ölçmek için kullanılan temel gösterge.",
        short_definition_de="Ein messbarer Wert, der zeigt, wie effektiv Ziele erreicht werden.",
        short_definition_ar="قيمة قابلة للقياس تُظهر مدى فعالية تحقيق الأهداف.",
        definition_en="A Key Performance Indicator is a measurable value used to evaluate how effectively a company, department, or individual is achieving key business objectives, such as revenue, win rate, or conversion rate.",
        definition_tr="KPI, bir şirketin, departmanın veya çalışanın temel iş hedeflerine (gelir, kazanma oranı, dönüşüm oranı gibi) ne kadar etkili ilerlediğini değerlendirmek için kullanılan ölçülebilir bir değerdir.",
        definition_de="Eine Leistungskennzahl (KPI) ist ein messbarer Wert, der zur Bewertung herangezogen wird, wie effektiv ein Unternehmen, eine Abteilung oder eine Person zentrale Geschäftsziele wie Umsatz, Gewinnrate oder Konversionsrate erreicht.",
        definition_ar="مؤشر الأداء الرئيسي هو قيمة قابلة للقياس تُستخدم لتقييم مدى فعالية تحقيق شركة أو قسم أو فرد لأهداف الأعمال الرئيسية، مثل الإيرادات أو معدل الفوز أو معدل التحويل.",
    ),
    dict(
        key="forecast",
        category="business_intelligence",
        term_en="Forecast",
        term_tr="Tahmin (Forecast)",
        term_de="Prognose",
        term_ar="التوقعات (Forecast)",
        short_definition_en="A projection of expected future sales or revenue.",
        short_definition_tr="Gelecekte gerçekleşmesi beklenen satış veya gelir tahmini.",
        short_definition_de="Eine Projektion des erwarteten zukünftigen Umsatzes.",
        short_definition_ar="توقع للمبيعات أو الإيرادات المتوقعة في المستقبل.",
        definition_en="A sales forecast is a data-driven projection of expected future revenue, typically based on pipeline value, historical win rates, and deal probability.",
        definition_tr="Satış tahmini, genellikle pipeline değeri, geçmiş kazanma oranları ve fırsat olasılığına dayanan, gelecekteki beklenen gelirin veriye dayalı bir projeksiyonudur.",
        definition_de="Eine Umsatzprognose ist eine datenbasierte Projektion des erwarteten zukünftigen Umsatzes, die in der Regel auf dem Pipeline-Wert, historischen Gewinnraten und der Abschlusswahrscheinlichkeit basiert.",
        definition_ar="توقع المبيعات هو تقدير مستقبلي للإيرادات المتوقعة يعتمد على البيانات، ويُبنى عادة على قيمة خط الأنابيب البيعي ومعدلات الفوز التاريخية واحتمالية إغلاق الصفقة.",
    ),
    dict(
        key="mrr",
        category="finance",
        term_en="MRR (Monthly Recurring Revenue)",
        term_tr="MRR (Aylık Tekrarlayan Gelir)",
        term_de="MRR (Monatlich wiederkehrender Umsatz)",
        term_ar="الإيراد الشهري المتكرر (MRR)",
        short_definition_en="The predictable revenue a business expects to receive every month.",
        short_definition_tr="Bir işletmenin her ay tahsil etmeyi beklediği tekrarlayan gelir.",
        short_definition_de="Der vorhersehbare Umsatz, den ein Unternehmen jeden Monat erwartet.",
        short_definition_ar="الإيراد المتوقع الذي تحصل عليه الشركة كل شهر بشكل متكرر.",
        definition_en="Monthly Recurring Revenue is the predictable total revenue generated from all active subscriptions or recurring contracts in a given month.",
        definition_tr="MRR, belirli bir aydaki tüm aktif abonelik veya tekrarlayan sözleşmelerden elde edilen öngörülebilir toplam gelirdir.",
        definition_de="Der monatlich wiederkehrende Umsatz ist der vorhersehbare Gesamtumsatz, der aus allen aktiven Abonnements oder wiederkehrenden Verträgen in einem bestimmten Monat generiert wird.",
        definition_ar="الإيراد الشهري المتكرر هو الإجمالي المتوقع للإيرادات المتحققة من جميع الاشتراكات النشطة أو العقود المتكررة خلال شهر معين.",
    ),
    dict(
        key="arr",
        category="finance",
        term_en="ARR (Annual Recurring Revenue)",
        term_tr="ARR (Yıllık Tekrarlayan Gelir)",
        term_de="ARR (Jährlich wiederkehrender Umsatz)",
        term_ar="الإيراد السنوي المتكرر (ARR)",
        short_definition_en="Monthly Recurring Revenue annualized (MRR x 12).",
        short_definition_tr="Aylık tekrarlayan gelirin yıllıklaştırılmış hali (MRR x 12).",
        short_definition_de="Der jährlich hochgerechnete monatlich wiederkehrende Umsatz (MRR x 12).",
        short_definition_ar="الإيراد الشهري المتكرر محسوبًا على أساس سنوي (MRR × 12).",
        definition_en="Annual Recurring Revenue is the yearly value of recurring revenue from subscriptions, typically calculated as MRR multiplied by 12. It is a core SaaS growth metric.",
        definition_tr="ARR, aboneliklerden elde edilen tekrarlayan gelirin yıllık değeridir ve genellikle MRR'nin 12 ile çarpılmasıyla hesaplanır. SaaS şirketleri için temel bir büyüme metriğidir.",
        definition_de="Der jährlich wiederkehrende Umsatz ist der jährliche Wert des wiederkehrenden Umsatzes aus Abonnements, üblicherweise berechnet als MRR multipliziert mit 12.",
        definition_ar="الإيراد السنوي المتكرر هو القيمة السنوية للإيرادات المتكررة من الاشتراكات، ويُحسب عادة بضرب الإيراد الشهري المتكرر في 12.",
    ),
    dict(
        key="sla",
        category="management",
        term_en="SLA (Service Level Agreement)",
        term_tr="SLA (Hizmet Seviyesi Anlaşması)",
        term_de="SLA (Service Level Agreement)",
        term_ar="اتفاقية مستوى الخدمة (SLA)",
        short_definition_en="An agreement defining the expected level and standards of a service.",
        short_definition_tr="Bir hizmetin kalite ve süre standartlarını tanımlayan anlaşma.",
        short_definition_de="Eine Vereinbarung, die das erwartete Niveau und die Standards einer Dienstleistung definiert.",
        short_definition_ar="اتفاقية تحدد المستوى والمعايير المتوقعة لتقديم خدمة معينة.",
        definition_en="A Service Level Agreement defines the standard of service a provider commits to, including response times, uptime, and quality metrics.",
        definition_tr="SLA, bir hizmet sağlayıcının taahhüt ettiği hizmet standardını; yanıt süreleri, çalışma süresi ve kalite metriklerini tanımlar.",
        definition_de="Ein Service Level Agreement definiert den Servicestandard, zu dem sich ein Anbieter verpflichtet, einschließlich Reaktionszeiten, Verfügbarkeit und Qualitätskennzahlen.",
        definition_ar="اتفاقية مستوى الخدمة تحدد معيار الخدمة الذي يلتزم به مزود الخدمة، بما في ذلك أوقات الاستجابة ونسبة التشغيل ومقاييس الجودة.",
    ),
    dict(
        key="gross_margin",
        category="finance",
        term_en="Gross Margin",
        term_tr="Brüt Kâr Marjı",
        term_de="Bruttomarge",
        term_ar="الهامش الإجمالي",
        short_definition_en="Revenue remaining after subtracting the cost of goods sold, as a percentage.",
        short_definition_tr="Satılan malın maliyeti çıkarıldıktan sonra kalan gelirin yüzdesi.",
        short_definition_de="Der verbleibende Umsatz nach Abzug der Herstellungskosten, in Prozent.",
        short_definition_ar="نسبة الإيراد المتبقي بعد خصم تكلفة البضاعة المباعة.",
        definition_en="Gross margin is the percentage of revenue remaining after subtracting the direct cost of producing or delivering goods and services (COGS).",
        definition_tr="Brüt kâr marjı, mal ve hizmetlerin üretim veya teslimatının doğrudan maliyeti (COGS) çıkarıldıktan sonra kalan gelirin yüzdesidir.",
        definition_de="Die Bruttomarge ist der Prozentsatz des Umsatzes, der nach Abzug der direkten Kosten für die Herstellung oder Bereitstellung von Waren und Dienstleistungen (COGS) übrig bleibt.",
        definition_ar="الهامش الإجمالي هو النسبة المئوية للإيراد المتبقي بعد خصم التكلفة المباشرة لإنتاج أو تقديم السلع والخدمات.",
    ),
    dict(
        key="pipeline_velocity",
        category="analytics",
        term_en="Pipeline Velocity",
        term_tr="Pipeline Hızı (Velocity)",
        term_de="Pipeline-Geschwindigkeit",
        term_ar="سرعة خط الأنابيب البيعي",
        short_definition_en="How quickly opportunities move through the pipeline and generate revenue.",
        short_definition_tr="Satış pipeline'ındaki fırsatların ne kadar hızlı ilerlediğini ölçen metrik.",
        short_definition_de="Wie schnell Chancen die Pipeline durchlaufen und Umsatz generieren.",
        short_definition_ar="مقياس لمدى سرعة تقدم الفرص عبر خط الأنابيب البيعي وتحقيقها للإيرادات.",
        definition_en="Pipeline velocity measures how quickly deals move through the sales pipeline and translate into revenue. It is typically calculated as (number of opportunities x win rate x average deal size) / sales cycle length.",
        definition_tr="Pipeline velocity, fırsatların satış hunisinde ne kadar hızlı ilerleyip gelire dönüştüğünü ölçer. Genellikle (fırsat sayısı x kazanma oranı x ortalama fırsat büyüklüğü) / satış döngüsü uzunluğu olarak hesaplanır.",
        definition_de="Die Pipeline-Geschwindigkeit misst, wie schnell Deals die Vertriebspipeline durchlaufen und in Umsatz umgewandelt werden. Sie wird üblicherweise als (Anzahl der Chancen x Gewinnrate x durchschnittliche Dealgröße) / Verkaufszykluslänge berechnet.",
        definition_ar="تقيس سرعة خط الأنابيب البيعي مدى سرعة تقدم الصفقات عبر مسار المبيعات وتحويلها إلى إيرادات، وتُحسب عادة كـ (عدد الفرص × معدل الفوز × متوسط حجم الصفقة) ÷ مدة دورة المبيعات.",
    ),
    dict(
        key="win_rate",
        category="sales",
        term_en="Win Rate",
        term_tr="Kazanma Oranı (Win Rate)",
        term_de="Gewinnrate",
        term_ar="معدل الفوز",
        short_definition_en="The percentage of sales opportunities that end in a successful deal.",
        short_definition_tr="Kazanılan satış fırsatlarının toplam satış fırsatlarına oranı.",
        short_definition_de="Der Prozentsatz der Verkaufschancen, die zu einem erfolgreichen Abschluss führen.",
        short_definition_ar="النسبة المئوية للفرص البيعية التي تنتهي بصفقة ناجحة.",
        definition_en="Win rate is the percentage of sales opportunities that result in a successful (closed-won) deal, out of all opportunities that reached a final decision (won or lost).",
        definition_tr="Win rate, nihai bir karara ulaşan tüm fırsatlar (kazanılan veya kaybedilen) içinde başarıyla kapanan (kazanılan) fırsatların yüzdesidir.",
        definition_de="Die Gewinnrate ist der Prozentsatz der Verkaufschancen, die zu einem erfolgreichen (gewonnenen) Abschluss führen, gemessen an allen Chancen, die zu einer endgültigen Entscheidung (gewonnen oder verloren) gekommen sind.",
        definition_ar="معدل الفوز هو النسبة المئوية للفرص البيعية التي تنتهي بصفقة ناجحة (فوز) من إجمالي الفرص التي وصلت إلى قرار نهائي (فوز أو خسارة).",
    ),
    dict(
        key="customer_360",
        category="crm",
        term_en="Customer 360",
        term_tr="360 Derece Müşteri Görünümü",
        term_de="Customer 360",
        term_ar="رؤية 360 للعميل",
        short_definition_en="A complete, unified view of a customer across every touchpoint.",
        short_definition_tr="Bir müşterinin tüm etkileşim noktalarındaki tam ve birleşik görünümü.",
        short_definition_de="Eine vollständige, einheitliche Sicht auf einen Kunden über alle Kontaktpunkte hinweg.",
        short_definition_ar="نظرة شاملة وموحدة للعميل عبر جميع نقاط التواصل.",
        definition_en="Customer 360 refers to a unified view that aggregates every interaction, deal, contact, and communication a company has had with a customer into a single profile.",
        definition_tr="Customer 360, bir şirketin bir müşteriyle olan tüm etkileşimlerini, fırsatlarını, kişilerini ve iletişim geçmişini tek bir profilde birleştiren görünümü ifade eder.",
        definition_de="Customer 360 bezeichnet eine einheitliche Sicht, die jede Interaktion, jeden Deal, Kontakt und jede Kommunikation, die ein Unternehmen mit einem Kunden hatte, in einem einzigen Profil zusammenfasst.",
        definition_ar="تشير رؤية 360 للعميل إلى عرض موحد يجمع كل تفاعل وصفقة وجهة اتصال واتصال أجرته الشركة مع العميل في ملف واحد.",
    ),
    dict(
        key="rbac",
        category="software",
        term_en="RBAC (Role-Based Access Control)",
        term_tr="RBAC (Rol Bazlı Erişim Kontrolü)",
        term_de="RBAC (Rollenbasierte Zugriffskontrolle)",
        term_ar="التحكم في الوصول المستند إلى الأدوار (RBAC)",
        short_definition_en="Restricting system access based on a user's assigned role.",
        short_definition_tr="Sistem erişiminin kullanıcının rolüne göre kısıtlanması.",
        short_definition_de="Einschränkung des Systemzugriffs basierend auf der zugewiesenen Rolle eines Benutzers.",
        short_definition_ar="تقييد الوصول إلى النظام بناءً على الدور المخصص للمستخدم.",
        definition_en="Role-Based Access Control restricts system access and actions based on a user's assigned role (e.g. Admin, Manager, Sales Rep), enforced on the backend rather than only hidden in the UI.",
        definition_tr="RBAC, sistem erişimini ve işlemleri kullanıcının atanmış rolüne (Admin, Manager, Sales Rep vb.) göre kısıtlar; bu kontrol yalnızca arayüzde değil, backend'de de uygulanır.",
        definition_de="Die rollenbasierte Zugriffskontrolle schränkt den Systemzugriff und die Aktionen basierend auf der zugewiesenen Rolle eines Benutzers (z. B. Admin, Manager, Vertriebsmitarbeiter) ein und wird im Backend durchgesetzt.",
        definition_ar="يقيّد التحكم في الوصول المستند إلى الأدوار الوصول إلى النظام والإجراءات بناءً على الدور المخصص للمستخدم (مثل المسؤول أو المدير أو مندوب المبيعات)، ويُفرض على مستوى الخادم لا الواجهة فقط.",
    ),
    dict(
        key="dashboard",
        category="business_intelligence",
        term_en="Dashboard",
        term_tr="Gösterge Paneli (Dashboard)",
        term_de="Dashboard",
        term_ar="لوحة المعلومات",
        short_definition_en="A visual display of key metrics for at-a-glance monitoring.",
        short_definition_tr="Temel metriklerin tek bakışta izlenmesini sağlayan görsel ekran.",
        short_definition_de="Eine visuelle Anzeige wichtiger Kennzahlen zur Überwachung auf einen Blick.",
        short_definition_ar="عرض مرئي للمقاييس الرئيسية لمتابعتها بنظرة واحدة.",
        definition_en="A dashboard is a visual interface that consolidates key performance indicators and charts into a single view, enabling managers to monitor business health at a glance.",
        definition_tr="Dashboard, temel performans göstergelerini ve grafikleri tek bir ekranda birleştiren, yöneticilerin iş sağlığını tek bakışta izlemesini sağlayan görsel bir arayüzdür.",
        definition_de="Ein Dashboard ist eine visuelle Oberfläche, die wichtige Leistungskennzahlen und Diagramme in einer einzigen Ansicht zusammenfasst, damit Manager den Geschäftszustand auf einen Blick überwachen können.",
        definition_ar="لوحة المعلومات هي واجهة مرئية تجمع مؤشرات الأداء الرئيسية والرسوم البيانية في عرض واحد، مما يتيح للمديرين متابعة صحة الأعمال بنظرة واحدة.",
    ),
    dict(
        key="segmentation",
        category="marketing",
        term_en="Customer Segmentation",
        term_tr="Müşteri Segmentasyonu",
        term_de="Kundensegmentierung",
        term_ar="تجزئة العملاء",
        short_definition_en="Dividing customers into groups sharing similar characteristics.",
        short_definition_tr="Müşterilerin benzer özelliklere göre gruplara ayrılması.",
        short_definition_de="Aufteilung der Kunden in Gruppen mit ähnlichen Merkmalen.",
        short_definition_ar="تقسيم العملاء إلى مجموعات تتشارك خصائص متشابهة.",
        definition_en="Customer segmentation is the practice of dividing customers into groups based on shared characteristics such as company size, industry, or revenue, so that sales and marketing efforts can be tailored effectively.",
        definition_tr="Müşteri segmentasyonu, şirket büyüklüğü, sektör veya gelir gibi ortak özelliklere göre müşterilerin gruplara ayrılması, böylece satış ve pazarlama çalışmalarının etkili şekilde uyarlanabilmesi pratiğidir.",
        definition_de="Kundensegmentierung ist die Praxis, Kunden anhand gemeinsamer Merkmale wie Unternehmensgröße, Branche oder Umsatz in Gruppen einzuteilen, damit Vertriebs- und Marketingmaßnahmen effektiv angepasst werden können.",
        definition_ar="تجزئة العملاء هي ممارسة تقسيم العملاء إلى مجموعات بناءً على خصائص مشتركة مثل حجم الشركة أو القطاع أو الإيرادات، بما يتيح تخصيص جهود المبيعات والتسويق بفعالية.",
    ),
    dict(
        key="ybs",
        category="ybs",
        term_en="Management Information System (MIS)",
        term_tr="Yönetim Bilişim Sistemi (YBS)",
        term_de="Managementinformationssystem (MIS)",
        term_ar="نظام المعلومات الإداري",
        short_definition_en="A system converting raw operational data into information for management decisions.",
        short_definition_tr="Ham operasyonel veriyi yönetim kararları için bilgiye dönüştüren sistem.",
        short_definition_de="Ein System, das operative Rohdaten in Informationen für Managemententscheidungen umwandelt.",
        short_definition_ar="نظام يحوّل البيانات التشغيلية الخام إلى معلومات تدعم قرارات الإدارة.",
        definition_en="A Management Information System collects raw operational data, processes it into structured information, and presents it as analysis that supports management decision-making - following the Data -> Information -> Analysis -> Decision chain.",
        definition_tr="Yönetim Bilişim Sistemi, ham operasyonel veriyi toplar, yapılandırılmış bilgiye dönüştürür ve yönetim kararlarını destekleyen bir analiz olarak sunar; bu, Veri -> Bilgi -> Analiz -> Karar zincirini takip eder.",
        definition_de="Ein Managementinformationssystem sammelt operative Rohdaten, verarbeitet sie zu strukturierten Informationen und präsentiert sie als Analyse, die die Managemententscheidung unterstützt - der Kette Daten -> Information -> Analyse -> Entscheidung folgend.",
        definition_ar="يجمع نظام المعلومات الإداري البيانات التشغيلية الخام، ويحوّلها إلى معلومات منظمة، ويقدمها كتحليل يدعم اتخاذ القرار الإداري، متبعًا سلسلة البيانات ← المعلومات ← التحليل ← القرار.",
    ),
    dict(
        key="business_intelligence",
        category="business_intelligence",
        term_en="Business Intelligence (BI)",
        term_tr="İş Zekası (BI)",
        term_de="Business Intelligence (BI)",
        term_ar="ذكاء الأعمال",
        short_definition_en="Technologies and practices for analyzing business data to support decisions.",
        short_definition_tr="İş verilerini analiz ederek karar almayı destekleyen teknoloji ve pratikler.",
        short_definition_de="Technologien und Praktiken zur Analyse von Geschäftsdaten zur Entscheidungsunterstützung.",
        short_definition_ar="تقنيات وممارسات لتحليل بيانات الأعمال لدعم اتخاذ القرار.",
        definition_en="Business Intelligence encompasses the strategies and technologies used to collect, analyze, and present business data - such as revenue trends, funnels, and segmentation - to support better management decisions.",
        definition_tr="İş zekası, gelir trendleri, huniler ve segmentasyon gibi iş verilerini toplamak, analiz etmek ve daha iyi yönetim kararlarını desteklemek için sunmakta kullanılan strateji ve teknolojileri kapsar.",
        definition_de="Business Intelligence umfasst die Strategien und Technologien zum Sammeln, Analysieren und Präsentieren von Geschäftsdaten - wie Umsatztrends, Funnels und Segmentierung - zur Unterstützung besserer Managemententscheidungen.",
        definition_ar="يشمل ذكاء الأعمال الاستراتيجيات والتقنيات المستخدمة لجمع وتحليل وتقديم بيانات الأعمال - مثل اتجاهات الإيرادات ومسارات التحويل والتجزئة - لدعم قرارات إدارية أفضل.",
    ),
    dict(
        key="deal",
        category="crm",
        term_en="Deal",
        term_tr="Fırsat/Anlaşma (Deal)",
        term_de="Deal",
        term_ar="صفقة",
        short_definition_en="A tracked sales transaction moving through the pipeline toward a close.",
        short_definition_tr="Pipeline içinde kapanışa doğru ilerleyen, takip edilen satış işlemi.",
        short_definition_de="Ein verfolgter Verkaufsvorgang, der sich in der Pipeline auf einen Abschluss hin bewegt.",
        short_definition_ar="عملية بيع متتبعة تتقدم عبر خط الأنابيب نحو الإغلاق.",
        definition_en="A deal is the core CRM record representing a potential sale, tracked through pipeline stages, with an associated value, probability, owner, and expected close date, until it is marked Won or Lost.",
        definition_tr="Deal, potansiyel bir satışı temsil eden, pipeline aşamaları boyunca takip edilen, değer, olasılık, sahip ve beklenen kapanış tarihi ile ilişkilendirilmiş temel CRM kaydıdır; nihayetinde Kazanıldı veya Kaybedildi olarak işaretlenir.",
        definition_de="Ein Deal ist der zentrale CRM-Datensatz, der einen potenziellen Verkauf darstellt, durch Pipeline-Phasen verfolgt wird und mit Wert, Wahrscheinlichkeit, Inhaber und erwartetem Abschlussdatum verknüpft ist, bis er als gewonnen oder verloren markiert wird.",
        definition_ar="الصفقة هي السجل الأساسي في نظام إدارة علاقات العملاء الذي يمثل عملية بيع محتملة، ويتم تتبعها عبر مراحل خط الأنابيب، مع قيمة واحتمالية ومالك وتاريخ إغلاق متوقع، حتى يتم تصنيفها كفوز أو خسارة.",
    ),
    dict(
        key="probability",
        category="sales",
        term_en="Win Probability",
        term_tr="Kazanma Olasılığı",
        term_de="Gewinnwahrscheinlichkeit",
        term_ar="احتمالية الفوز",
        short_definition_en="The estimated likelihood, as a percentage, that a deal will close successfully.",
        short_definition_tr="Bir fırsatın başarıyla kapanma olasılığının yüzde olarak tahmini.",
        short_definition_de="Die geschätzte Wahrscheinlichkeit in Prozent, dass ein Deal erfolgreich abgeschlossen wird.",
        short_definition_ar="التقدير الاحتمالي (كنسبة مئوية) لإغلاق الصفقة بنجاح.",
        definition_en="Win probability is a percentage estimate, usually tied to the current pipeline stage, of how likely a deal is to close as Won. It is used to calculate weighted pipeline and revenue forecasts.",
        definition_tr="Kazanma olasılığı, genellikle mevcut pipeline aşamasına bağlı olarak, bir fırsatın Kazanıldı olarak kapanma ihtimalinin yüzde tahminidir. Ağırlıklı pipeline ve gelir tahminlerinin hesaplanmasında kullanılır.",
        definition_de="Die Gewinnwahrscheinlichkeit ist eine prozentuale Schätzung, meist an die aktuelle Pipeline-Phase gekoppelt, wie wahrscheinlich ein Deal als gewonnen abgeschlossen wird. Sie wird zur Berechnung gewichteter Pipeline- und Umsatzprognosen verwendet.",
        definition_ar="احتمالية الفوز هي تقدير بالنسبة المئوية، يرتبط عادة بمرحلة خط الأنابيب الحالية، لمدى احتمال إغلاق الصفقة بالفوز، ويُستخدم لحساب تنبؤات خط الأنابيب والإيرادات المرجحة.",
    ),
    dict(
        key="kanban",
        category="software",
        term_en="Kanban Board",
        term_tr="Kanban Panosu",
        term_de="Kanban-Board",
        term_ar="لوحة كانبان",
        short_definition_en="A visual board showing items as cards moving through workflow columns.",
        short_definition_tr="Öğelerin iş akışı sütunları arasında hareket eden kartlar olarak gösterildiği görsel pano.",
        short_definition_de="Ein visuelles Board, das Elemente als Karten zeigt, die sich durch Workflow-Spalten bewegen.",
        short_definition_ar="لوحة مرئية تعرض العناصر كبطاقات تنتقل بين أعمدة سير العمل.",
        definition_en="A Kanban board visualizes work items (such as deals or tasks) as cards that move across columns representing workflow stages, making bottlenecks and progress immediately visible.",
        definition_tr="Kanban panosu, iş öğelerini (fırsatlar veya görevler gibi) iş akışı aşamalarını temsil eden sütunlar arasında hareket eden kartlar olarak görselleştirir, tıkanıklıkları ve ilerlemeyi anında görünür kılar.",
        definition_de="Ein Kanban-Board visualisiert Arbeitselemente (wie Deals oder Aufgaben) als Karten, die sich über Spalten bewegen, die Workflow-Phasen darstellen, wodurch Engpässe und Fortschritt sofort sichtbar werden.",
        definition_ar="تعرض لوحة كانبان عناصر العمل (مثل الصفقات أو المهام) كبطاقات تتحرك بين أعمدة تمثل مراحل سير العمل، مما يجعل الاختناقات والتقدم واضحين فورًا.",
    ),
    dict(
        key="okr",
        category="management",
        term_en="OKR (Objectives and Key Results)",
        term_tr="OKR (Amaçlar ve Anahtar Sonuçlar)",
        term_de="OKR (Objectives and Key Results)",
        term_ar="الأهداف والنتائج الرئيسية (OKR)",
        short_definition_en="A goal-setting framework pairing qualitative objectives with measurable key results.",
        short_definition_tr="Nitel amaçları ölçülebilir anahtar sonuçlarla eşleştiren bir hedef belirleme çerçevesi.",
        short_definition_de="Ein Zielsetzungs-Framework, das qualitative Ziele mit messbaren Kennzahlen verbindet.",
        short_definition_ar="إطار لتحديد الأهداف يربط الأهداف النوعية بنتائج رئيسية قابلة للقياس.",
        definition_en="OKRs pair a qualitative Objective (what you want to achieve) with a small set of quantitative Key Results (how you'll know you got there), used to align teams around a shared, measurable goal each quarter.",
        definition_tr="OKR, nitel bir Amaç (neyi başarmak istediğiniz) ile ölçülebilir birkaç Anahtar Sonucu (oraya vardığınızı nasıl anlayacağınız) eşleştirir; ekipleri her çeyrekte ortak, ölçülebilir bir hedef etrafında hizalamak için kullanılır.",
        definition_de="OKRs verbinden ein qualitatives Ziel (Objective) mit einer kleinen Anzahl messbarer Schlüsselergebnisse (Key Results), um Teams jedes Quartal auf ein gemeinsames, messbares Ziel auszurichten.",
        definition_ar="يربط إطار OKR هدفًا نوعيًا (ما تريد تحقيقه) بمجموعة صغيرة من النتائج الرئيسية القابلة للقياس (كيف ستعرف أنك وصلت)، ويُستخدم لمواءمة الفرق حول هدف مشترك وقابل للقياس كل ربع سنة.",
    ),
    dict(
        key="roas",
        category="marketing",
        term_en="ROAS (Return on Ad Spend)",
        term_tr="ROAS (Reklam Harcaması Getirisi)",
        term_de="ROAS (Return on Ad Spend)",
        term_ar="عائد الإنفاق الإعلاني (ROAS)",
        short_definition_en="Revenue generated for every currency unit spent on advertising.",
        short_definition_tr="Reklama harcanan her para birimi başına elde edilen gelir.",
        short_definition_de="Der pro ausgegebener Werbewährungseinheit erzielte Umsatz.",
        short_definition_ar="الإيراد المتحقق مقابل كل وحدة عملة يتم إنفاقها على الإعلانات.",
        definition_en="Return on Ad Spend measures the revenue earned for every unit of currency spent on a specific advertising campaign, calculated as revenue attributed to the campaign divided by its cost.",
        definition_tr="ROAS, belirli bir reklam kampanyasına harcanan her para birimi karşılığında kazanılan geliri ölçer; kampanyaya atfedilen gelirin kampanya maliyetine bölünmesiyle hesaplanır.",
        definition_de="Return on Ad Spend misst den Umsatz, der für jede in eine bestimmte Werbekampagne investierte Währungseinheit erzielt wird, berechnet als der Kampagne zugeordneter Umsatz geteilt durch ihre Kosten.",
        definition_ar="يقيس عائد الإنفاق الإعلاني الإيراد المكتسب مقابل كل وحدة عملة يتم إنفاقها على حملة إعلانية معينة، ويُحسب بقسمة الإيراد المنسوب إلى الحملة على تكلفتها.",
    ),
    dict(
        key="ebitda",
        category="finance",
        term_en="EBITDA",
        term_tr="FAVÖK (EBITDA)",
        term_de="EBITDA",
        term_ar="الأرباح قبل الفوائد والضرائب والإهلاك (EBITDA)",
        short_definition_en="Earnings before interest, taxes, depreciation and amortization - a proxy for core operating profitability.",
        short_definition_tr="Faiz, vergi, amortisman ve itfa öncesi kâr - temel operasyonel kârlılığın bir göstergesi.",
        short_definition_de="Gewinn vor Zinsen, Steuern und Abschreibungen - ein Näherungswert für die operative Kernrentabilität.",
        short_definition_ar="الأرباح قبل الفوائد والضرائب والإهلاك - مؤشر تقريبي للربحية التشغيلية الأساسية.",
        definition_en="EBITDA (Earnings Before Interest, Taxes, Depreciation and Amortization) strips out financing and accounting decisions to show how profitable a company's core operations are, which is why it's widely used to compare companies with different capital structures.",
        definition_tr="FAVÖK (EBITDA), finansman ve muhasebe kararlarını dışlayarak bir şirketin temel operasyonlarının ne kadar kârlı olduğunu gösterir; bu nedenle farklı sermaye yapılarına sahip şirketleri karşılaştırmak için yaygın olarak kullanılır.",
        definition_de="EBITDA (Gewinn vor Zinsen, Steuern und Abschreibungen) blendet Finanzierungs- und Bilanzierungsentscheidungen aus, um zu zeigen, wie profitabel das Kerngeschäft eines Unternehmens ist - deshalb wird es häufig zum Vergleich von Unternehmen mit unterschiedlichen Kapitalstrukturen verwendet.",
        definition_ar="تستبعد EBITDA قرارات التمويل والمحاسبة لإظهار مدى ربحية العمليات الأساسية للشركة، ولهذا تُستخدم على نطاق واسع لمقارنة الشركات ذات الهياكل الرأسمالية المختلفة.",
    ),
    dict(
        key="net_revenue",
        category="finance",
        term_en="Net Revenue",
        term_tr="Net Gelir",
        term_de="Nettoumsatz",
        term_ar="صافي الإيراد",
        short_definition_en="Total revenue after subtracting discounts, returns, and refunds.",
        short_definition_tr="İndirimler, iadeler ve geri ödemeler düşüldükten sonraki toplam gelir.",
        short_definition_de="Gesamtumsatz nach Abzug von Rabatten, Retouren und Rückerstattungen.",
        short_definition_ar="إجمالي الإيراد بعد خصم الخصومات والمرتجعات والمبالغ المستردة.",
        definition_en="Net revenue is gross revenue minus discounts, product returns, and refunds - the figure that reflects what a company actually keeps from its sales before accounting for the cost of delivering them.",
        definition_tr="Net gelir, brüt gelirden indirimler, ürün iadeleri ve geri ödemeler çıkarıldıktan sonra kalan tutardır; bir şirketin satışlarından, teslimat maliyetleri hesaba katılmadan önce fiilen elde tuttuğu tutarı yansıtır.",
        definition_de="Der Nettoumsatz ist der Bruttoumsatz abzüglich Rabatten, Produktretouren und Rückerstattungen - die Zahl, die zeigt, was ein Unternehmen tatsächlich von seinen Verkäufen behält, bevor die Lieferkosten berücksichtigt werden.",
        definition_ar="صافي الإيراد هو الإيراد الإجمالي مطروحًا منه الخصومات ومرتجعات المنتجات والمبالغ المستردة - وهو الرقم الذي يعكس ما تحتفظ به الشركة فعليًا من مبيعاتها قبل احتساب تكلفة تسليمها.",
    ),
    dict(
        key="retention_rate",
        category="analytics",
        term_en="Retention Rate",
        term_tr="Elde Tutma Oranı",
        term_de="Kundenbindungsrate",
        term_ar="معدل الاحتفاظ",
        short_definition_en="The percentage of customers a company keeps over a given period.",
        short_definition_tr="Bir şirketin belirli bir dönemde elinde tuttuğu müşterilerin yüzdesi.",
        short_definition_de="Der Prozentsatz der Kunden, die ein Unternehmen über einen bestimmten Zeitraum behält.",
        short_definition_ar="النسبة المئوية للعملاء الذين تحتفظ بهم الشركة خلال فترة معينة.",
        definition_en="Retention rate is the percentage of customers still active at the end of a period out of those active at the start, and is effectively the inverse of churn rate - a higher retention rate means a healthier, more durable revenue base.",
        definition_tr="Elde tutma oranı, bir dönemin başında aktif olan müşterilerden dönem sonunda hâlâ aktif olanların yüzdesidir ve churn rate'in tersidir; daha yüksek bir elde tutma oranı daha sağlıklı ve kalıcı bir gelir tabanı anlamına gelir.",
        definition_de="Die Kundenbindungsrate ist der Prozentsatz der zu Beginn eines Zeitraums aktiven Kunden, die am Ende des Zeitraums noch aktiv sind, und ist im Wesentlichen die Umkehrung der Abwanderungsrate.",
        definition_ar="معدل الاحتفاظ هو النسبة المئوية للعملاء الذين ما زالوا نشطين في نهاية فترة معينة من إجمالي من كانوا نشطين في بدايتها، وهو عكس معدل التسرب فعليًا.",
    ),
    dict(
        key="customer_acquisition",
        category="marketing",
        term_en="Customer Acquisition",
        term_tr="Müşteri Kazanımı",
        term_de="Kundengewinnung",
        term_ar="اكتساب العملاء",
        short_definition_en="The process of bringing new customers into a business.",
        short_definition_tr="Bir işletmeye yeni müşteriler kazandırma süreci.",
        short_definition_de="Der Prozess, neue Kunden für ein Unternehmen zu gewinnen.",
        short_definition_ar="عملية جلب عملاء جدد إلى الشركة.",
        definition_en="Customer acquisition covers the full set of marketing and sales activities used to convert prospects into paying customers; its efficiency is typically measured against Customer Acquisition Cost (CAC) and the resulting Lifetime Value (LTV).",
        definition_tr="Müşteri kazanımı, potansiyel müşterileri ödeme yapan müşterilere dönüştürmek için kullanılan tüm pazarlama ve satış faaliyetlerini kapsar; verimliliği genellikle Müşteri Edinme Maliyeti (CAC) ve elde edilen Yaşam Boyu Değer (LTV) ile ölçülür.",
        definition_de="Kundengewinnung umfasst alle Marketing- und Vertriebsaktivitäten, mit denen Interessenten in zahlende Kunden umgewandelt werden; ihre Effizienz wird typischerweise anhand der Kundenakquisitionskosten (CAC) und des daraus resultierenden Customer Lifetime Value (LTV) gemessen.",
        definition_ar="يشمل اكتساب العملاء مجموعة كاملة من أنشطة التسويق والمبيعات المستخدمة لتحويل العملاء المحتملين إلى عملاء فعليين؛ وتُقاس كفاءته عادةً مقارنةً بتكلفة اكتساب العميل (CAC) والقيمة الدائمة الناتجة (LTV).",
    ),
    dict(
        key="sales_cycle",
        category="sales",
        term_en="Sales Cycle",
        term_tr="Satış Döngüsü",
        term_de="Verkaufszyklus",
        term_ar="دورة المبيعات",
        short_definition_en="The average time it takes to move a deal from first contact to close.",
        short_definition_tr="Bir fırsatın ilk temastan kapanışa kadar geçen ortalama süresi.",
        short_definition_de="Die durchschnittliche Zeit, die ein Deal vom Erstkontakt bis zum Abschluss benötigt.",
        short_definition_ar="متوسط الوقت الذي تستغرقه الصفقة من أول تواصل حتى إغلاقها.",
        definition_en="The sales cycle is the average length of time, usually in days, between a deal's creation and its close (won or lost); shortening it is one of the main levers for increasing pipeline velocity.",
        definition_tr="Satış döngüsü, bir fırsatın oluşturulması ile kapanması (kazanılması veya kaybedilmesi) arasında geçen, genellikle gün cinsinden ifade edilen ortalama süredir; bu süreyi kısaltmak, pipeline hızını artırmanın temel yollarından biridir.",
        definition_de="Der Verkaufszyklus ist die durchschnittliche Zeitspanne, meist in Tagen, zwischen der Erstellung eines Deals und seinem Abschluss (gewonnen oder verloren); seine Verkürzung ist einer der wichtigsten Hebel zur Steigerung der Pipeline-Geschwindigkeit.",
        definition_ar="دورة المبيعات هي متوسط الوقت، عادة بالأيام، بين إنشاء الصفقة وإغلاقها (فوزًا أو خسارة)؛ ويُعد تقصيرها أحد أهم وسائل زيادة سرعة خط الأنابيب.",
    ),
    dict(
        key="quota",
        category="sales",
        term_en="Quota",
        term_tr="Kota",
        term_de="Quote",
        term_ar="الحصة (Quota)",
        short_definition_en="The revenue or unit sales goal assigned to a sales rep for a given period.",
        short_definition_tr="Bir satış temsilcisine belirli bir dönem için atanan gelir veya satış adedi hedefi.",
        short_definition_de="Das einem Vertriebsmitarbeiter für einen bestimmten Zeitraum zugewiesene Umsatz- oder Absatzziel.",
        short_definition_ar="هدف الإيراد أو عدد الوحدات المخصص لمندوب المبيعات خلال فترة معينة.",
        definition_en="A quota is the individual revenue or unit-sales target a sales representative is expected to hit in a period (usually monthly or quarterly); achievement against quota is the most common way to measure individual sales performance.",
        definition_tr="Kota, bir satış temsilcisinin belirli bir dönemde (genellikle aylık veya çeyreklik) ulaşması beklenen bireysel gelir veya satış adedi hedefidir; kotaya karşı başarı, bireysel satış performansını ölçmenin en yaygın yoludur.",
        definition_de="Eine Quote ist das individuelle Umsatz- oder Absatzziel, das ein Vertriebsmitarbeiter in einem Zeitraum (meist monatlich oder vierteljährlich) erreichen soll; die Zielerreichung ist die gängigste Methode zur Messung der individuellen Vertriebsleistung.",
        definition_ar="الحصة هي هدف الإيراد أو عدد الوحدات الفردي الذي يُتوقع من مندوب المبيعات تحقيقه خلال فترة (شهرية أو ربع سنوية عادة)؛ وتحقيق الحصة هو الطريقة الأكثر شيوعًا لقياس أداء المبيعات الفردي.",
    ),
    dict(
        key="funnel",
        category="marketing",
        term_en="Funnel",
        term_tr="Huni (Funnel)",
        term_de="Trichter (Funnel)",
        term_ar="القمع (Funnel)",
        short_definition_en="A visualization of how prospects narrow down from awareness to purchase.",
        short_definition_tr="Potansiyel müşterilerin farkındalıktan satın almaya kadar daralmasının görselleştirilmesi.",
        short_definition_de="Eine Visualisierung, wie sich Interessenten von der Aufmerksamkeit bis zum Kauf verringern.",
        short_definition_ar="تصور مرئي لكيفية تناقص العملاء المحتملين من مرحلة الوعي إلى الشراء.",
        definition_en="A funnel visualizes how a group of prospects narrows at each stage of a process - marketing funnels track awareness to signup, sales funnels track lead to closed deal - making drop-off points and conversion rates easy to spot.",
        definition_tr="Huni, bir grup potansiyel müşterinin bir sürecin her aşamasında nasıl daraldığını görselleştirir; pazarlama hunileri farkındalıktan kayda, satış hunileri ise lead'den kapanan fırsata kadar takip eder ve kayıp noktalarını fark etmeyi kolaylaştırır.",
        definition_de="Ein Funnel visualisiert, wie sich eine Gruppe von Interessenten in jeder Phase eines Prozesses verringert - Marketing-Funnels verfolgen von der Aufmerksamkeit bis zur Anmeldung, Sales-Funnels von Lead bis zum Abschluss.",
        definition_ar="يصور القمع كيفية تناقص مجموعة من العملاء المحتملين في كل مرحلة من مراحل العملية - تتتبع قمع التسويق من الوعي إلى التسجيل، وتتتبع قمع المبيعات من العميل المحتمل إلى الصفقة المغلقة.",
    ),
    dict(
        key="roi",
        category="finance",
        term_en="ROI (Return on Investment)",
        term_tr="ROI (Yatırım Getirisi)",
        term_de="ROI (Kapitalrendite)",
        term_ar="عائد الاستثمار (ROI)",
        short_definition_en="The profit generated from an investment relative to its cost.",
        short_definition_tr="Bir yatırımdan elde edilen kârın, o yatırımın maliyetine oranı.",
        short_definition_de="Der aus einer Investition erzielte Gewinn im Verhältnis zu ihren Kosten.",
        short_definition_ar="الربح المتحقق من استثمار ما مقارنة بتكلفته.",
        definition_en="Return on Investment measures the profitability of an investment as (Gain - Cost) / Cost, expressed as a percentage - a general-purpose metric used to compare the efficiency of very different kinds of spending, from ad campaigns to new hires.",
        definition_tr="Yatırım Getirisi (ROI), bir yatırımın kârlılığını (Kazanç - Maliyet) / Maliyet olarak, yüzde şeklinde ölçer; reklam kampanyalarından yeni işe alımlara kadar çok farklı türde harcamaların verimliliğini karşılaştırmak için kullanılan genel amaçlı bir metriktir.",
        definition_de="Der Return on Investment misst die Rentabilität einer Investition als (Gewinn - Kosten) / Kosten, ausgedrückt in Prozent - eine universelle Kennzahl zum Vergleich der Effizienz sehr unterschiedlicher Ausgabenarten.",
        definition_ar="يقيس عائد الاستثمار ربحية استثمار ما بالمعادلة (الربح - التكلفة) ÷ التكلفة، معبرًا عنه كنسبة مئوية - وهو مقياس عام يُستخدم لمقارنة كفاءة أنواع مختلفة تمامًا من الإنفاق.",
    ),
    dict(
        key="profit_margin",
        category="finance",
        term_en="Profit Margin",
        term_tr="Kâr Marjı",
        term_de="Gewinnmarge",
        term_ar="هامش الربح",
        short_definition_en="The percentage of revenue that remains as profit after expenses.",
        short_definition_tr="Giderler düşüldükten sonra gelirin kâr olarak kalan yüzdesi.",
        short_definition_de="Der Prozentsatz des Umsatzes, der nach Abzug der Ausgaben als Gewinn verbleibt.",
        short_definition_ar="النسبة المئوية من الإيراد التي تبقى كربح بعد خصم المصروفات.",
        definition_en="Profit margin expresses profit as a percentage of revenue; net profit margin (net income / revenue) is the most complete version, showing how much of every sale actually turns into bottom-line profit after all costs.",
        definition_tr="Kâr marjı, kârı gelirin yüzdesi olarak ifade eder; net kâr marjı (net gelir / gelir) en kapsamlı versiyondur ve tüm maliyetler sonrasında her satışın ne kadarının gerçekten net kâra dönüştüğünü gösterir.",
        definition_de="Die Gewinnmarge drückt den Gewinn als Prozentsatz des Umsatzes aus; die Nettogewinnmarge (Nettoeinkommen / Umsatz) ist die vollständigste Version und zeigt, wie viel von jedem Verkauf nach allen Kosten tatsächlich zu Gewinn wird.",
        definition_ar="يعبر هامش الربح عن الربح كنسبة مئوية من الإيراد؛ ويُعد هامش الربح الصافي (صافي الدخل ÷ الإيراد) النسخة الأكثر شمولاً، إذ يوضح مقدار ما يتحول فعليًا إلى ربح صافٍ من كل عملية بيع بعد جميع التكاليف.",
    ),
    dict(
        key="average_deal_size",
        category="sales",
        term_en="Average Deal Size",
        term_tr="Ortalama Fırsat Büyüklüğü",
        term_de="Durchschnittliche Dealgröße",
        term_ar="متوسط حجم الصفقة",
        short_definition_en="The average monetary value of won deals over a period.",
        short_definition_tr="Belirli bir dönemde kazanılan fırsatların ortalama parasal değeri.",
        short_definition_de="Der durchschnittliche monetäre Wert gewonnener Deals über einen Zeitraum.",
        short_definition_ar="متوسط القيمة النقدية للصفقات المكسوبة خلال فترة معينة.",
        definition_en="Average deal size is total won revenue divided by the number of won deals in a period; tracking it over time shows whether a sales team is moving upmarket (larger deals) or downmarket (smaller, more frequent deals).",
        definition_tr="Ortalama fırsat büyüklüğü, bir dönemdeki toplam kazanılan gelirin, kazanılan fırsat sayısına bölünmesiyle bulunur; zaman içindeki takibi, satış ekibinin üst pazara (daha büyük fırsatlar) mı yoksa alt pazara (daha küçük, daha sık fırsatlar) mı kaydığını gösterir.",
        definition_de="Die durchschnittliche Dealgröße ist der gesamte gewonnene Umsatz geteilt durch die Anzahl der gewonnenen Deals in einem Zeitraum; ihre Entwicklung zeigt, ob ein Vertriebsteam sich zu größeren oder kleineren, häufigeren Deals bewegt.",
        definition_ar="متوسط حجم الصفقة هو إجمالي الإيراد المكسوب مقسومًا على عدد الصفقات المكسوبة خلال فترة؛ ويُظهر تتبعه عبر الزمن ما إذا كان فريق المبيعات يتجه نحو صفقات أكبر أو صفقات أصغر وأكثر تكرارًا.",
    ),
    dict(
        key="sales_velocity",
        category="analytics",
        term_en="Sales Velocity",
        term_tr="Satış Hızı",
        term_de="Vertriebsgeschwindigkeit",
        term_ar="سرعة المبيعات",
        short_definition_en="How quickly a sales team generates revenue, combining deal count, size, win rate and cycle length.",
        short_definition_tr="Bir satış ekibinin, fırsat sayısı, büyüklüğü, kazanma oranı ve döngü süresini birleştirerek ne kadar hızlı gelir ürettiği.",
        short_definition_de="Wie schnell ein Vertriebsteam Umsatz generiert, unter Berücksichtigung von Dealanzahl, -größe, Gewinnrate und Zykluslänge.",
        short_definition_ar="مدى سرعة توليد فريق المبيعات للإيرادات، بدمج عدد الصفقات وحجمها ومعدل الفوز ومدة الدورة.",
        definition_en="Sales velocity is a single composite metric - (number of opportunities x win rate x average deal size) / sales cycle length - that summarizes how quickly a sales organization turns pipeline into revenue; it is the same formula behind Pipeline Velocity.",
        definition_tr="Satış hızı, (fırsat sayısı x kazanma oranı x ortalama fırsat büyüklüğü) / satış döngüsü uzunluğu şeklinde tek bir bileşik metriktir ve bir satış organizasyonunun pipeline'ı ne kadar hızlı gelire dönüştürdüğünü özetler; Pipeline Velocity ile aynı formüle dayanır.",
        definition_de="Die Vertriebsgeschwindigkeit ist eine einzelne zusammengesetzte Kennzahl - (Anzahl der Chancen x Gewinnrate x durchschnittliche Dealgröße) / Verkaufszykluslänge - die zusammenfasst, wie schnell eine Vertriebsorganisation Pipeline in Umsatz umwandelt.",
        definition_ar="سرعة المبيعات هي مقياس مركب واحد - (عدد الفرص × معدل الفوز × متوسط حجم الصفقة) ÷ مدة دورة المبيعات - يلخص مدى سرعة تحويل منظمة المبيعات لخط الأنابيب إلى إيرادات.",
    ),
    dict(
        key="customer_growth",
        category="analytics",
        term_en="Customer Growth",
        term_tr="Müşteri Büyümesi",
        term_de="Kundenwachstum",
        term_ar="نمو العملاء",
        short_definition_en="The rate at which a company's active customer base increases over time.",
        short_definition_tr="Bir şirketin aktif müşteri tabanının zaman içinde büyüme oranı.",
        short_definition_de="Die Rate, mit der die aktive Kundenbasis eines Unternehmens im Laufe der Zeit wächst.",
        short_definition_ar="المعدل الذي تنمو به قاعدة العملاء النشطين للشركة بمرور الوقت.",
        definition_en="Customer growth tracks the net change in active customers over a period (new customers won minus customers lost), and is usually read alongside revenue growth to check whether expansion is coming from more customers, bigger deals, or both.",
        definition_tr="Müşteri büyümesi, bir dönemdeki aktif müşteri sayısındaki net değişimi (kazanılan yeni müşteriler eksi kaybedilen müşteriler) takip eder ve büyümenin daha fazla müşteriden mi, daha büyük fırsatlardan mı yoksa her ikisinden mi geldiğini kontrol etmek için genellikle gelir büyümesiyle birlikte okunur.",
        definition_de="Das Kundenwachstum verfolgt die Nettoveränderung der aktiven Kunden über einen Zeitraum (neu gewonnene Kunden minus verlorene Kunden) und wird meist zusammen mit dem Umsatzwachstum betrachtet.",
        definition_ar="يتتبع نمو العملاء صافي التغير في عدد العملاء النشطين خلال فترة معينة (العملاء الجدد المكتسبون مطروحًا منهم العملاء المفقودون)، ويُقرأ عادة جنبًا إلى جنب مع نمو الإيرادات.",
    ),
]
